'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {useAccount} from './AccountContext';
import {agentTemplates} from '@/lib/catalog';
import {inferBlueprintCategory} from '@/lib/agent-blueprints';
import './AgentPortfolio.css';
export default function AgentRequest(){const account=useAccount();const [brief,setBrief]=useState<Record<string,string>>({outcome:'',department:'',targetUsers:'',systems:'',volume:'',sensitivity:''});const [requests,setRequests]=useState<{id:string;status:string;brief:Record<string,string>}[]>([]);const [error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(''),[preview,setPreview]=useState(false);
 useEffect(()=>{if(account.mode==='demo')return;const abort=new AbortController();fetch('/api/workspace/agent-requests',{cache:'no-store',signal:abort.signal}).then(async r=>{if(!r.ok)throw Error('Unable to load requests.');return r.json()}).then(setRequests).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort()},[account.mode]);
 const matches=brief.outcome?agentTemplates.filter(a=>a.categories.includes(inferBlueprintCategory(brief.outcome))).slice(0,3):[];
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;if(account.mode==='demo'){setPreview(true);return}setBusy(true);setError('');try{const r=await fetch('/api/workspace/agent-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId:account.workspaceId,brief})});const d=await r.json();if(!r.ok)throw Error(d.error);setSaved(d.id);setRequests(v=>[{...d,brief},...v])}catch(e){setError(e instanceof Error?e.message:'Unable to submit.')}finally{setBusy(false)}}
 return <section className="agentRequest"><Link href="/agents/catalog">← Agent Catalog</Link><div className="pageHead"><div><h1>Request a New Agent</h1><p>Tell NEWNEO the outcome you need. We review fit before adding a new profile.</p></div></div>{saved?<section className="panel" role="status"><h2>Request recorded</h2><p>Reference: {saved}</p><p>Pending product review. No Agent was created or activated.</p><p>The review determines whether an existing Agent fits, additional Skills are needed, or a new profile is appropriate.</p></section>:<form className="panel" onSubmit={submit}>{Object.entries({outcome:'Desired business outcome',department:'Department',targetUsers:'Target users',systems:'Systems involved',volume:'Expected volume',sensitivity:'Data sensitivity'}).map(([key,label])=><label key={key}>{label}{key==='outcome'?<textarea required rows={3} maxLength={2000} value={brief[key]} onChange={e=>setBrief(v=>({...v,[key]:e.target.value}))}/>:<input required maxLength={key==='systems'?1000:key==='targetUsers'?500:key==='volume'?200:100} value={brief[key]} onChange={e=>setBrief(v=>({...v,[key]:e.target.value}))}/>}</label>)}<footer><button className="button primary" disabled={busy||account.mode!=='demo'&&!account.workspace?.can_edit_agents}>{busy?'Submitting…':account.mode==='demo'?'Preview request':'Submit request for review'}</button>{preview&&<p role="status">Demo preview only. No request was sent and no Agent was created.</p>}</footer></form>}{error&&<p role="alert">{error}</p>}{matches.length>0&&!saved&&<section className="panel requestResults"><h2>Profiles to consider</h2><p>Suggested by business topic. NEWNEO still needs to review systems, Skills and data requirements.</p>{matches.map(a=><Link key={a.id} href={`/agents/catalog/${a.id}`}>{a.name} →</Link>)}</section>}{requests.length>0&&<section className="panel requestResults"><h2>Workspace requests</h2>{requests.map(r=><div key={r.id}><strong>{r.brief.outcome}</strong><p>{r.status} · {r.id}</p></div>)}</section>}</section>
}
