'use client';
import {useState} from 'react';
import Link from 'next/link';
import {AgentIcon} from './Assets';
import {FilterChip} from './UI';
import {catalogFilters,filterAgents,type AgentTemplate} from '@/lib/catalog';
import './AgentPortfolio.css';
export function AgentCard({agent}:{agent:AgentTemplate;featured?:boolean}){return <article className="agentCard hybridCatalogCard"><Link href={`/agents/catalog/${agent.id}`} aria-label={`Review ${agent.name}`}><div className="catalogCardTop"><AgentIcon type={agent.type}/><span className="modelPill">{agent.complexity??'Medium'} complexity</span></div><h2>{agent.name}</h2><p>{agent.description}</p><dl className="agentProfileFacts"><div><dt>Outcomes</dt><dd>{agent.defaultSuccessMetrics.slice(0,2).join(' · ')}</dd></div><div><dt>Core Skills</dt><dd>{agent.recommendedSkills.filter(s=>!s.optional).slice(0,3).map(s=>s.name).join(' · ')}</dd></div><div><dt>Expected systems</dt><dd>{agent.recommendedKnowledgeTypes.filter(s=>!s.optional).map(s=>s.name).join(' · ')}</dd></div><div><dt>Typical use</dt><dd>{agent.expectedTaskProfile}</dd></div><div><dt>Maturity</dt><dd>Blueprint · workspace validation required</dd></div></dl><span className="profileLink">Review Agent →</span></Link></article>}
export default function AgentCatalog(){const [filter,setFilter]=useState('All'),[search,setSearch]=useState('');const agents=filterAgents(filter).filter(a=>`${a.name} ${a.description} ${a.tags.join(' ')}`.toLowerCase().includes(search.trim().toLowerCase()));return <div className="catalog"><div className="pageHead"><div><h1>Agent Catalog</h1><p>Select a NEWNEO Agent. Connect your business context, review and activate.</p></div><Link className="button secondary" href="/agents/request">Request a New Agent</Link></div><label className="catalogSearch">Find an Agent<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search agents, capabilities or departments…"/></label><div className="filterRow" aria-label="Agent categories">{catalogFilters.map(c=><FilterChip key={c} active={filter===c} onClick={()=>setFilter(c)}>{c} ({String(filterAgents(c).length).padStart(2,'0')})</FilterChip>)}</div><section className="agentGrid" aria-label="NEWNEO Agent profiles" tabIndex={0}>{agents.map(a=><AgentCard key={a.id} agent={a}/>)}</section>{!agents.length&&<section className="panel"><h2>No matching Agent</h2><Link href="/agents/request">Can’t find what you need? Request an Agent →</Link></section>}</div>}
