'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {getTemplate} from '@/lib/catalog';
import {profileLabel,matchRecommendation,type Recommendation} from '@/lib/agent-blueprints';
import {skillLibrary} from '@/lib/skills';
import {useAccount} from './AccountContext';
import './AgentPortfolio.css';
export default function AgentIntroduction({templateId}:{templateId:string}){
 const a=getTemplate(templateId),account=useAccount();const [skills,setSkills]=useState<{id:string;name:string}[]>([]),[status,setStatus]=useState('Loading Skill Library…');
 useEffect(()=>{if(account.mode==='demo'){setSkills(skillLibrary);setStatus('Demo Skill Library');return}const abort=new AbortController();fetch('/api/workspace/registry',{cache:'no-store',signal:abort.signal}).then(async r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setSkills(d.skills.filter((s:{archived_at?:string})=>!s.archived_at));setStatus('Workspace Skill Library')}).catch(e=>{if(e.name!=='AbortError')setStatus('Skill Library unavailable. Bindings must be reviewed before activation.')});return ()=>abort.abort()},[account.mode]);
 const list=(items:Recommendation[])=> <ul>{items.map(r=><li key={r.id}><strong>{r.name}</strong>{r.highRisk&&<small>Approval required before enabling</small>}</li>)}</ul>;
 const skillList=(items:Recommendation[])=><ul>{items.map(r=>{const s=skills.find(s=>matchRecommendation(s.name,r));return <li key={r.id}>{s?<Link href={`/skills/${s.id}`}>{s.name} ↗</Link>:<strong>{r.name}</strong>}<small>{s?'From Skill Library':'Profile capability · library binding required'}{r.highRisk?' · human approval required':''}</small></li>})}</ul>;
 return <section className="agentIntroduction"><Link href="/agents/catalog">← Agent Catalog</Link><header className="pageHead"><div><span className="tag">NEWNEO Agent Profile</span><h1>{a.name}</h1><p>{a.description}</p></div><div className="profileActions"><Link className="button secondary" href={`/agents/launch?template=${a.id}&customize=1`}>Customize</Link><Link className="button primary" href={`/agents/launch?template=${a.id}`}>Use this Agent →</Link></div></header><div className="profileSummary"><div><small>Target users</small><strong>{a.defaultTargetUsers}</strong></div><div><small>Outcomes</small><strong>{a.defaultSuccessMetrics.slice(0,2).join(' · ')}</strong></div><div><small>Profile maturity</small><strong>Blueprint · validate in your workspace</strong></div></div><div className="profilePanels"><article className="panel"><h2>Skills & outcomes</h2><p>{status}</p><h3>Core Skills</h3>{skillList(a.recommendedSkills.filter(s=>!s.optional))}<h3>Optional Skills</h3>{a.recommendedSkills.some(s=>s.optional)?skillList(a.recommendedSkills.filter(s=>s.optional)):<p>Additional Skills can be added from the library.</p>}<h3>Expected outcomes</h3><ul>{a.defaultSuccessMetrics.map(s=><li key={s}>{s}</li>)}</ul></article><article className="panel"><h2>Connect your context</h2><h3>Knowledge sources</h3>{list(a.recommendedKnowledgeTypes.filter(s=>!s.optional))}<h3>Expected actions</h3>{list(a.recommendedTools)}<p>Available sources and Skills are preselected during review. Missing connections remain explicit.</p></article><article className="panel"><h2>Recommended intelligence</h2><h3>{a.recommendedInfrastructure}</h3><p>{a.infrastructureReason}</p><h3>{profileLabel(a.recommendedModelProfile)}</h3><p>Model selection requires an available, organization-approved model.</p><h3>Governance defaults</h3>{list(a.recommendedGovernancePolicies)}<details><summary>Recommended Evaluation Suite ({a.recommendedEvaluationSuite.length})</summary>{list(a.recommendedEvaluationSuite)}</details></article></div><p className="surfaceMuted">Select → Connect → Confirm → Activate. Profile recommendations do not grant permissions or certify production readiness.</p></section>
}
