'use client';
import {useState,type FormEvent} from 'react';
import Link from 'next/link';
import {Cloud,LockKeyhole,Cpu,Check,SlidersHorizontal} from 'lucide-react';
import {getTemplate} from '@/lib/catalog';
import {buildBlueprint,modelPreferences,preferredProfile,profileLabel,matchRecommendation,type Blueprint,type Recommendation} from '@/lib/agent-blueprints';
import {LaunchStepper} from './LaunchStepper';
import {NeoMascot} from './NeoMascot';
import type {RegistryEditorProps} from './WorkspaceRegistry';
import './WorkspaceAgentWizard.css';
const stages=['Use Case','Knowledge','Tools & MCP','Infrastructure','Model','Governance','Evaluate','Deploy'];
const titles=['Review your agent’s mission','Review recommended knowledge','Review skills and actions','Review infrastructure','Review the model recommendation','Review protection & governance','Review the evaluation suite','Your Agent Profile'];
const planKeys=['skillPlan','knowledgePlan','toolPlan','governancePlan','evaluationPlan'] as const;
function readPlan(raw:string|undefined,fallback:string[]){try{const p=JSON.parse(raw??'');return Array.isArray(p)&&p.every(i=>typeof i==='string')?p:fallback}catch{return fallback}}
const defaultNames=(items:Recommendation[])=>items.filter(r=>!r.optional&&!r.highRisk).map(r=>r.name);
export function blueprintDefaults(b:Blueprint,templateId:string){return {blueprintTemplateId:templateId,mission:b.defaultMission,targetUsers:b.defaultTargetUsers,businessOwner:b.suggestedBusinessOwner,successMetrics:b.defaultSuccessMetrics.join('\n'),criticality:b.defaultCriticality,infrastructure:b.recommendedInfrastructure,model:profileLabel(b.recommendedModelProfile),modelPreference:'Balanced',modelProfile:JSON.stringify(b.recommendedModelProfile),environment:'Staging',skillPlan:JSON.stringify(defaultNames(b.recommendedSkills)),knowledgePlan:JSON.stringify(defaultNames(b.recommendedKnowledgeTypes)),toolPlan:JSON.stringify(defaultNames(b.recommendedTools)),governancePlan:JSON.stringify(defaultNames(b.recommendedGovernancePolicies)),evaluationPlan:JSON.stringify(defaultNames(b.recommendedEvaluationSuite))}}
export default function AgentBlueprintWizard({resource,latest,data,workspaceId,onCancel,onSaved,templateId}:RegistryEditorProps){
 const initialTemplateId=latest?.configuration.blueprintTemplateId||templateId||'custom';
 const template=getTemplate(initialTemplateId);const isCustom=initialTemplateId==='custom';
 const initialBlueprint=isCustom?buildBlueprint({...template,objective:latest?.configuration.mission||'',targetUsers:latest?.configuration.targetUsers||template.targetUsers}):template;
 const [blueprint,setBlueprint]=useState<Blueprint>(initialBlueprint);
 const [proposed,setProposed]=useState(!isCustom||Boolean(latest?.configuration.mission));
 const [values,setValues]=useState<Record<string,string>>({...blueprintDefaults(initialBlueprint,initialTemplateId),name:resource?.name??(isCustom?'':template.name),description:resource?.description??(isCustom?'':template.description),...latest?.configuration});
 const initialBindings=()=>latest?Object.fromEntries(data.bindings.filter(b=>b.agent_version_id===latest.id).map(b=>{const v=data.skillVersions.find(v=>v.id===b.skill_version_id);return [v?.skill_id??'',b.skill_version_id]})):recommendedBindings(initialBlueprint);
 function recommendedBindings(b:Blueprint){return Object.fromEntries(data.skills.filter(s=>!s.archived_at&&b.recommendedSkills.some(r=>!r.optional&&!r.highRisk&&matchRecommendation(s.name,r))).flatMap(s=>{const v=data.skillVersions.filter(v=>v.skill_id===s.id).sort((a,b)=>b.number-a.number)[0];return v?[[s.id,v.id]]:[]}))}
 function recommendedDocuments(b:Blueprint){return data.documents.filter(d=>!d.archived_at&&b.recommendedKnowledgeTypes.some(r=>!r.optional&&matchRecommendation(d.title,r))).map(d=>d.id)}
 const [bindings,setBindings]=useState<Record<string,string>>(initialBindings);
 const [documents,setDocuments]=useState<string[]>(()=>latest?data.knowledgeBindings.filter(b=>b.agent_version_id===latest.id).map(b=>b.document_id):recommendedDocuments(initialBlueprint));
 const [step,setStep]=useState(0);const [reviewed,setReviewed]=useState<number[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [savedId,setSavedId]=useState('');const [checked,setChecked]=useState('');
 const defaults=blueprintDefaults(blueprint,initialTemplateId);
 const plan=(key:typeof planKeys[number])=>readPlan(values[key],readPlan(defaults[key],[]));
 const fingerprint=JSON.stringify([values,bindings,documents]);
 const edit=(key:string,value:string)=>{setValues(v=>({...v,[key]:value}));setReviewed(r=>r.filter(n=>n!==step&&n<6));setChecked('')};
 const toggle=(key:typeof planKeys[number],name:string,selected:boolean)=>{
 edit(key,JSON.stringify(selected?[...plan(key).filter(n=>n!==name),name]:plan(key).filter(n=>n!==name)));
 const recommendation={id:name,name,reason:''};
 if(key==='knowledgePlan'){const matches=data.documents.filter(d=>!d.archived_at&&matchRecommendation(d.title,recommendation)).map(d=>d.id);setDocuments(ids=>selected?[...new Set([...ids,...matches])]:ids.filter(id=>!matches.includes(id)))}
 if(key==='skillPlan'){setBindings(current=>{const result={...current};for(const s of data.skills.filter(s=>!s.archived_at&&matchRecommendation(s.name,recommendation))){const v=data.skillVersions.filter(v=>v.skill_id===s.id).sort((a,b)=>b.number-a.number)[0];if(selected&&v)result[s.id]=v.id;else delete result[s.id]}return result})}
 };
 const stageKeys=[['name','mission','description','businessOwner','targetUsers','successMetrics','criticality'],['knowledgePlan'],['skillPlan','toolPlan'],['infrastructure'],['model','modelPreference'],['governancePlan','governanceNotes'],['evaluationPlan'],['environment']];
 const comparison={...defaults,name:isCustom?values.name:template.name,description:isCustom?values.description:template.description,governanceNotes:''};
 const stageCustomized=(index:number)=>stageKeys[index].some(key=>{const a=values[key]??'',b=(comparison as Record<string,string>)[key]??'';if(planKeys.includes(key as typeof planKeys[number]))return [...readPlan(a,[])].sort().join('|')!==[...readPlan(b,[])].sort().join('|');return a!==b})||(index===1&&[...documents].sort().join('|')!==recommendedDocuments(blueprint).sort().join('|'))||(index===2&&Object.entries(bindings).filter(([,v])=>v).sort().join('|')!==Object.entries(recommendedBindings(blueprint)).sort().join('|'));
 const deviations=stages.filter((_,i)=>stageCustomized(i));
 const valid=Boolean(values.name?.trim()&&values.mission?.trim());
 const unavailable=data.skills.some(s=>s.archived_at&&bindings[s.id])||data.documents.some(d=>d.archived_at&&documents.includes(d.id));
 const linkedSkills=data.skills.filter(s=>Boolean(bindings[s.id]));
 const missingSkills=plan('skillPlan').filter(name=>!linkedSkills.some(s=>matchRecommendation(s.name,{id:name,name,reason:''})));
 const missingKnowledge=plan('knowledgePlan').filter(name=>!data.documents.some(d=>documents.includes(d.id)&&!d.archived_at&&matchRecommendation(d.title,{id:name,name,reason:''})));
 // No organization runtime/model approval registry exists yet. Fail closed for execution.
 const runtimeAvailable=false;
 const gates=[...(!valid?['Agent name and mission are required.']:[]),...(unavailable?['Remove archived skill/document references.']:[]),...(missingSkills.length?[`${missingSkills.length} planned skills need library bindings.`]:[]),...(missingKnowledge.length?[`${missingKnowledge.length} knowledge recommendations need connections or source bindings.`]:[]),...(plan('toolPlan').length?['Tool connections and permissions require validation.']:[]),'Model approval and runtime activation are pending.','Governance enforcement and production evaluation are pending.'];
 const fastPath=valid&&!unavailable&&!missingSkills.length&&!missingKnowledge.length&&runtimeAvailable;
 function propose(){const b=buildBlueprint({...template,objective:values.mission,targetUsers:values.targetUsers||template.targetUsers});setBlueprint(b);setValues(v=>({...v,...blueprintDefaults(b,'custom'),name:v.name,description:v.description,mission:v.mission,targetUsers:v.targetUsers||b.defaultTargetUsers,businessOwner:!v.businessOwner||v.businessOwner===blueprint.suggestedBusinessOwner?b.suggestedBusinessOwner:v.businessOwner}));setBindings(recommendedBindings(b));setDocuments(recommendedDocuments(b));setProposed(true);setReviewed([]);setChecked('')}
 function next(){if(!valid){setStep(0);setError('Review the agent name and mission before continuing.');return}if(step===0&&isCustom&&!proposed)propose();setError('');setReviewed(r=>[...new Set([...r,step])]);setStep(n=>Math.min(7,n+1))}
 async function save(e:FormEvent){e.preventDefault();if(step!==7||!valid||unavailable||busy)return;setBusy(true);setError('');try{const response=await fetch('/api/workspace/registry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,kind:'agent',id:resource?.id,revision:resource?.revision,name:values.name,description:values.description,configuration:{...values,modelProfile:JSON.stringify(preferredProfile(blueprint.recommendedModelProfile,values.modelPreference))},skillVersionIds:Object.values(bindings).filter(Boolean),documentIds:documents})});const result=await response.json();if(!response.ok)throw Error(result.error||'Unable to save blueprint.');setSavedId(result.id)}catch(e){setError(e instanceof Error?e.message:'Unable to save blueprint.')}finally{setBusy(false)}}
 const field=(key:string,label:string,max:number,multiline=false)=><label key={key}>{label}{multiline?<textarea rows={2} maxLength={max} value={values[key]??''} onChange={e=>{edit(key,e.target.value);if(isCustom&&key==='mission')setProposed(false)}}/>:<input maxLength={max} value={values[key]??''} onChange={e=>edit(key,e.target.value)}/>}</label>;
 function recommendations(items:Recommendation[],key:typeof planKeys[number],status:(r:Recommendation)=>string){return <div className="agentWizardOptions blueprintOptions">{items.map(r=><label className="agentWizardOption" key={r.id}><input type="checkbox" checked={plan(key).includes(r.name)} disabled={r.highRisk} onChange={e=>toggle(key,r.name,e.target.checked)}/><span><strong>{r.name}</strong><small>{r.highRisk?'Approval required · Optional / Advanced':r.optional?'Optional':'Recommended'} · {status(r)}</small><small>{r.reason}</small></span></label>)}</div>}
 if(savedId)return <section className="agentWizardSuccess panel"><NeoMascot state="success" size={180}/><h1>{resource?'Agent blueprint updated':'Hello, my name is Neo!'}</h1><p>{values.name} · Blueprint saved for {values.environment}.</p><p>Pending connections, approvals and evaluations are retained for review. No deployment occurred.</p><button className="button primary" onClick={()=>onSaved(savedId)}>View Agent →</button></section>;
 return <form className="workspaceAgentWizard journeyReference" onSubmit={save}>
 <header className="agentWizardHeading"><strong>{resource?'Review New Version':`Add Agent · ${isCustom?'Custom':template.name}`}</strong>{!resource&&<Link href="/agents/catalog">← Templates</Link>}<button className="button secondary" type="button" disabled={busy} onClick={onCancel}>Cancel</button></header>
 <LaunchStepper current={step} completed={stages.map((_,i)=>reviewed.includes(i))} onStep={n=>{if(!busy){setStep(n);setError('')}}}/>
 <div className="agentWizardWorkspace"><section className="agentWizardMain"><header><div className="blueprintStageCaption"><span className="agentWizardEyebrow">0{step+1} / {stages[step].toUpperCase()}</span><span className="blueprintBadge">{stageCustomized(step)?<><SlidersHorizontal size={12}/> Customized</>:<><Check size={12}/> Recommended</>}</span></div><h1>{titles[step]}</h1></header>
 <fieldset disabled={busy} className="agentWizardBody">
 <div className="agentWizardNotice blueprintIntelligence"><strong>NEWNEO Recommended Configuration</strong><span>{isCustom&&!proposed?'Describe the business outcome. NEWNEO will propose a blueprint for you to review.':'Preconfigured enterprise patterns. Review and adjust only where needed.'}</span></div>
 {step===0&&<><div className="agentWizardFields blueprintFields">{field('name','Agent name *',120)}{field('businessOwner','Suggested business owner',200)}{field('mission','Mission *',2000,true)}{field('description','Business purpose',2000,true)}{field('targetUsers','Target users',500)}{field('expectedVolume','Expected volume',200)}{field('dataRestrictions','Data restrictions',2000,true)}<label>Criticality<select value={values.criticality} onChange={e=>edit('criticality',e.target.value)}>{['Low','Medium','High'].map(v=><option key={v}>{v}</option>)}</select></label>{field('successMetrics','Success metrics',2000,true)}</div>{isCustom&&<button className="button secondary" type="button" disabled={!valid} onClick={propose}>{proposed?'Regenerate recommendations':'Propose recommended configuration'}</button>}</>}
 {step===1&&<>{recommendations(blueprint.recommendedKnowledgeTypes,'knowledgePlan',r=>data.documents.some(d=>documents.includes(d.id)&&!d.archived_at&&matchRecommendation(d.title,r))?'Available document linked':'Connection required')}<details className="blueprintCustomize"><summary>Customize workspace document bindings ({documents.length})</summary><p>Only available workspace documents are linked. A source recommendation does not create a connection.</p>{data.documents.filter(d=>!d.archived_at||documents.includes(d.id)).map(d=><label className="agentWizardOption" key={d.id}><input type="checkbox" checked={documents.includes(d.id)} onChange={e=>{setDocuments(e.target.checked?[...documents,d.id]:documents.filter(id=>id!==d.id));setChecked('');setReviewed(r=>r.filter(n=>n!==1))}}/><span>{d.title}{d.archived_at?' · Archived — remove':''}</span></label>)}{!data.documents.length&&<p>No workspace documents available.</p>}<Link target="_blank" href="/knowledge">Manage Knowledge ↗</Link></details></>}
 {step===2&&<><h2 className="blueprintSectionTitle">Preloaded skills</h2>{recommendations(blueprint.recommendedSkills,'skillPlan',r=>linkedSkills.some(s=>matchRecommendation(s.name,r))?'Library version linked':'Library binding required')}<details className="blueprintCustomize"><summary>Customize Skill Library versions ({linkedSkills.length} linked)</summary>{data.skills.filter(s=>!s.archived_at||bindings[s.id]).map(s=><label className="agentWizardOption" key={s.id}><span>{s.name}{s.archived_at?' · Archived — remove':''}</span><select value={bindings[s.id]??''} onChange={e=>{setBindings({...bindings,[s.id]:e.target.value});setChecked('');setReviewed(r=>r.filter(n=>n!==2))}}><option value="">Not linked</option>{data.skillVersions.filter(v=>v.skill_id===s.id).sort((a,b)=>b.number-a.number).map(v=><option key={v.id} value={v.id}>v{v.number}</option>)}</select></label>)}<Link href="/skills" target="_blank">Open Skill Library ↗</Link></details><h2 className="blueprintSectionTitle">Recommended Tools & MCP</h2>{recommendations(blueprint.recommendedTools,'toolPlan',()=> 'Planned · connection and permission review required')}</>}
 {step===3&&<><p>{blueprint.infrastructureReason}</p><div className="agentWizardOptions">{['Cloud','Private Cloud','Local / On-Prem','Hybrid'].map((name,i)=><label className="agentWizardOption" key={name}><input type="radio" name="infrastructure" checked={values.infrastructure===name} onChange={()=>edit('infrastructure',name)}/>{i===0?<Cloud/>:i===1?<><Cloud/><LockKeyhole size={16}/></>:i===2?<Cpu/>:<><Cloud/><LockKeyhole size={16}/><Cpu/></>}<span><strong>{name}</strong><small>{name===blueprint.recommendedInfrastructure?'Recommended':'Alternative'} · {['Managed operations','Dedicated data boundary','Local hardware and operations','Mixed execution and data boundaries'][i]}</small></span></label>)}</div><p className="agentWizardNotice">This saves the intended architecture. Residency, SLA, capacity and organization approval remain subject to validation.</p></>}
 {step===4&&<><label className="blueprintPreference">Optimize for<select value={values.modelPreference} onChange={e=>{const pref=e.target.value;setValues(v=>({...v,modelPreference:pref,model:profileLabel(preferredProfile(blueprint.recommendedModelProfile,pref))}));setChecked('');setReviewed(r=>r.filter(n=>n!==4))}}>{modelPreferences.map(p=><option key={p}>{p}</option>)}</select></label><div className="agentWizardNotice"><strong>{profileLabel(preferredProfile(blueprint.recommendedModelProfile,values.modelPreference))}</strong><p>{blueprint.expectedTaskProfile}. The recommendation specifies capabilities and remains provider-neutral.</p><small>Organization model approval: pending · No verified model catalog is connected.</small></div><div className="agentWizardOptions blueprintModelOptions">{[values.modelPreference,...modelPreferences.filter(p=>p!==values.modelPreference)].map(pref=>{const p=preferredProfile(blueprint.recommendedModelProfile,pref);return <label className="agentWizardOption" key={pref}><input type="radio" name="modelProfile" checked={values.modelPreference===pref} onChange={()=>{edit('modelPreference',pref);setValues(v=>({...v,model:profileLabel(p)}))}}/><span><strong>{pref}</strong><small>{profileLabel(p)}</small><small>Reasoning: {p.reasoning} · Latency target: {p.latency} · Cost sensitivity: {p.costSensitivity}</small><small>Context: {p.contextRequirement} · Multimodal: {p.multimodal?'required':'optional'} · Tool use: {p.toolUse}</small><small>Provider / model: pending approved catalog · These are requirements, not measured scores.</small></span></label>})}</div><details className="blueprintCustomize"><summary>Specify a preferred model or provider</summary>{field('model','Preferred model (approval required)',200)}</details></>}
 {step===5&&<><p>{plan('governancePlan').length} recommended policies included in this blueprint.</p>{recommendations(blueprint.recommendedGovernancePolicies,'governancePlan',()=> 'Planned · enforcement validation required')}<details className="blueprintCustomize"><summary>Customize governance requirements</summary>{field('governanceNotes','Additional requirements',2000,true)}</details></>}
 {step===6&&<>{recommendations(blueprint.recommendedEvaluationSuite,'evaluationPlan',()=> 'Not run')}<div className="blueprintEvaluationActions"><button className="button primary" type="button" disabled title="Requires an approved model, connected tools and an evaluation runtime">Run Recommended Evaluation</button><button className="button secondary" type="button" onClick={()=>setChecked(fingerprint)}>Check blueprint prerequisites</button></div><p>Execution is pending a validated runtime. Blueprint checks do not produce a model evaluation score.</p>{checked===fingerprint&&<div role="status" className="agentWizardNotice"><strong>Blueprint check completed · Production gates remain open</strong><ul>{gates.map(g=><li key={g}>{g}</li>)}</ul></div>}</>}
 {step===7&&<><p>{deviations.length?`${deviations.length} stages differ from NEWNEO recommended defaults: ${deviations.join(', ')}.`:'Recommended defaults retained.'}</p><dl className="surfaceFacts agentWizardSummary">{[['Mission',values.mission],['Skills',`${plan('skillPlan').length} planned · ${linkedSkills.length} library bindings`],['Knowledge',`${plan('knowledgePlan').length} recommended types · ${documents.length} documents`],['Tools',`${plan('toolPlan').length} planned · connections pending`],['Infrastructure',values.infrastructure],['Model',`${values.model} · approval pending`],['Governance',`${plan('governancePlan').length} policy requirements · enforcement pending`],['Evaluation',`${plan('evaluationPlan').length} scenarios · not run`]].map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl><label>Target environment<select value={values.environment} onChange={e=>edit('environment',e.target.value)}>{['Development','Staging','Production'].map(e=><option key={e}>{e}</option>)}</select></label><div className="agentWizardNotice"><strong>Recommended path: {blueprint.recommendedDeploymentPath.join(' → ')}</strong><p>Save for review. Production deployment remains blocked until connections, approvals and evaluations pass.</p></div><details><summary>Review deployment prerequisites ({gates.length})</summary><ul>{gates.map(g=><li key={g}>{g}</li>)}</ul></details></>}
 </fieldset></section><aside className="agentWizardReadiness panel"><header><strong>READINESS</strong><span>{Math.round(reviewed.length/8*100)}%</span></header><NeoMascot state="assembling" progress={Math.round(reviewed.length/8*100)} size={130}/><strong className="agentWizardPercent">{Math.round(reviewed.length/8*100)}%</strong><progress max={8} value={reviewed.length}/><p>{reviewed.length} of 8 stages reviewed</p><p>Current: <strong>{stages[step]}</strong></p><small>Blueprint review progress. Deployment gates are tracked separately.</small><button type="button" className="button secondary" disabled={!fastPath||busy} onClick={()=>{setReviewed([0,1,2,3,4,5]);setStep(6)}}>Accept Recommended Configuration</button>{!fastPath&&<small>Requires validated integrations, approvals and runtime.</small>}</aside></div>
 <footer className="agentWizardFooter">{error&&<p role="alert">{error}</p>}<button type="button" className="button secondary" disabled={busy} onClick={()=>step?setStep(step-1):onCancel()}>{step?'← Back':'Cancel'}</button>{step<7?<button key="confirm-stage" className="button primary" type="button" disabled={busy} onClick={e=>{e.preventDefault();next()}}>Confirm & Continue →</button>:<button key="save-blueprint" className="button primary" type="submit" disabled={busy||!valid||unavailable}>{busy?'Saving…':'Save blueprint for review'}</button>}</footer>
 </form>;
}
