'use client';

import {useState} from 'react';

const steps=['Use Case','Knowledge','Tools','Model','Governance','Evaluate','Deploy'];
const connectors=['SharePoint','Google Drive','Confluence','ServiceNow','Salesforce','Custom API'];
const tools=['ServiceNow','Salesforce','SAP','Microsoft Teams','Slack','Custom API'];

function ChoiceCard({title,body,selected,onClick}:{title:string,body:string,selected?:boolean,onClick?:()=>void}){return <button type="button" onClick={onClick} className={selected?'choiceCard selected':'choiceCard'}><b>{title}</b><span>{body}</span></button>}

export default function LaunchGuide(){
  const [step,setStep]=useState(0);
  const [runtime,setRuntime]=useState('Managed AI');
  const [selectedKnowledge,setSelectedKnowledge]=useState(['SharePoint']);
  const [selectedTools,setSelectedTools]=useState(['ServiceNow']);
  const toggle=(item:string,list:string[],setter:(v:string[])=>void)=>setter(list.includes(item)?list.filter(x=>x!==item):[...list,item]);
  const next=()=>setStep(v=>Math.min(6,v+1));
  const back=()=>setStep(v=>Math.max(0,v-1));
  return <>
    <div className="steps">{steps.map((s,i)=><button type="button" onClick={()=>setStep(i)} className={i===step?'step active':i<step?'step done':'step'} key={s}><i>{i+1}</i>{s}</button>)}</div>
    <section className="wizardCard">
      {step===0&&<div className="wizardGrid"><div><span className="eyebrow">Step 1 of 7</span><h2 className="wizardTitle">What should this agent accomplish?</h2><p className="wizardLead">Define the purpose and expected outcome. Newneo uses this context to guide later configuration.</p><div className="field"><label>Agent name</label><input className="input" defaultValue="Customer Service Agent"/></div><div className="field"><label>Business objective</label><textarea className="textarea" defaultValue="Help customers get accurate answers, resolve common issues and create support tickets when needed."/></div><div className="field"><label>Target users</label><select className="select" defaultValue="customers"><option value="customers">Customers</option><option value="employees">Employees</option><option value="partners">Partners</option><option value="mixed">Mixed audience</option></select></div><div className="field"><label>Primary goals</label><div className="checkList"><div className="check"><i>✓</i>Answer common questions</div><div className="check"><i>✓</i>Create support tickets</div><div className="check"><i>✓</i>Escalate complex issues</div><div className="check"><i>✓</i>Improve resolution time</div></div></div></div><aside className="sideHint"><h3>Expected outcomes</h3><ul><li>Reduce repetitive support work</li><li>Improve customer experience</li><li>Provide consistent assistance</li><li>Escalate sensitive requests safely</li></ul><div className="note">Keep this step business-focused. Technical choices come later.</div></aside></div>}
      {step===1&&<div><span className="eyebrow">Step 2 of 7</span><h2 className="wizardTitle">Connect the knowledge this agent can trust.</h2><p className="wizardLead">Use existing approved sources. Permissions remain governed by your organization.</p><div className="choiceGrid">{connectors.map(c=><ChoiceCard key={c} title={c} body={selectedKnowledge.includes(c)?'Connected':'Available to connect'} selected={selectedKnowledge.includes(c)} onClick={()=>toggle(c,selectedKnowledge,setSelectedKnowledge)}/>)}</div><div className="note">{selectedKnowledge.length} knowledge source{selectedKnowledge.length===1?'':'s'} selected. Advanced retrieval settings remain hidden unless needed.</div></div>}
      {step===2&&<div><span className="eyebrow">Step 3 of 7</span><h2 className="wizardTitle">What should this agent be allowed to do?</h2><p className="wizardLead">Add systems and actions. Newneo separates technical availability from approved agent permissions.</p><div className="choiceGrid">{tools.map(t=><ChoiceCard key={t} title={t} body={selectedTools.includes(t)?'Enabled for this agent':'Available'} selected={selectedTools.includes(t)} onClick={()=>toggle(t,selectedTools,setSelectedTools)}/>)}</div><div className="note">Actions can be restricted individually and can require human approval.</div></div>}
      {step===3&&<div><span className="eyebrow">Step 4 of 7</span><h2 className="wizardTitle">Where should this AI run?</h2><p className="wizardLead">Choose the operating model first. Detailed provider and runtime settings appear only when needed.</p><div className="choiceGrid four">{[['Managed AI','Use approved managed models and cloud AI services.'],['Customer Cloud','Run inside the organization’s AWS, Azure or GCP environment.'],['Private AI','Run inside a private or on-prem environment.'],['Hybrid','Combine approved private and cloud execution.']].map(([t,b])=><ChoiceCard key={t} title={t} body={b} selected={runtime===t} onClick={()=>setRuntime(t)}/>)}</div><div className="field compact"><label>Approved model</label><select className="select"><option>Organization Default — Recommended</option><option>Approved Model A</option><option>Approved Model B</option><option>Private Model Endpoint</option></select></div></div>}
      {step===4&&<div><span className="eyebrow">Step 5 of 7</span><h2 className="wizardTitle">Define the boundaries.</h2><p className="wizardLead">Make access and approval rules understandable before deployment.</p><div className="governGrid"><div className="panel flat"><h2>Access & permissions</h2><div className="checkList"><div className="check"><i>✓</i>Available to approved workspace users</div><div className="check"><i>✓</i>Require approval for sensitive actions</div><div className="check"><i>✓</i>Log all production interactions</div></div></div><div className="panel flat"><h2>Data controls</h2><div className="checkList"><div className="check"><i>✓</i>Respect source permissions</div><div className="check"><i>✓</i>Mask sensitive data where required</div><div className="check"><i>✓</i>Use approved data sources only</div></div></div></div><div className="note">This agent can read approved knowledge, create support tickets, and requires human approval for sensitive actions.</div></div>}
      {step===5&&<div><span className="eyebrow">Step 6 of 7</span><h2 className="wizardTitle">Test before production.</h2><p className="wizardLead">Mandatory evaluations must pass before the agent can be promoted.</p><div className="evalGrid"><div className="scoreRing"><strong>92%</strong><span>Evaluation score</span></div><div className="scoreList">{[['Task Success','94%'],['Groundedness','90%'],['Tool Success','96%'],['Policy Compliance','100%'],['Safety','98%']].map(([a,b])=><div className="scoreRow" key={a}><span>{a}</span><b>{b}</b></div>)}</div></div><div className="note">46 test cases passed, 3 need review, 1 failed non-mandatory scenario. Production gate is currently eligible.</div></div>}
      {step===6&&<div><span className="eyebrow">Step 7 of 7</span><h2 className="wizardTitle">Ready to deploy.</h2><p className="wizardLead">Review the configuration and select the target environment.</p><div className="deployGrid"><div className="summaryList">{[['Agent','Customer Service Agent'],['Knowledge',`${selectedKnowledge.length} sources connected`],['Tools',`${selectedTools.length} tools enabled`],['Runtime',runtime],['Governance','Organization policy enabled'],['Evaluation','92% — eligible']].map(([a,b])=><div className="summaryRow" key={a}><span>{a}</span><b>{b}</b></div>)}</div><div className="envChoices"><ChoiceCard title="Development" body="Internal testing"/><ChoiceCard title="Test" body="Pre-production validation"/><ChoiceCard title="Production" body="Live for approved users" selected/></div></div><div className="note">Production health checks and AgentOps monitoring will start automatically after deployment.</div></div>}
      <div className="wizardActions"><button type="button" className="button secondary" onClick={back} disabled={step===0}>← Back</button><button type="button" className="button primary" onClick={next}>{step===6?'Deploy to Production':'Next →'}</button></div>
    </section>
  </>
}
