'use client';
import {useState,useEffect,type ReactNode} from 'react';
import Link from 'next/link';
import {useAccount} from './AccountContext';
import {Metrics,Table,Status} from './hybrid/UI';
import './WorkspaceRegistry.css';
type Review={id:string;agent_version_id:string;requested_by:string;created_by:string;number:number;configuration:Record<string,string>;notes:string;created_at:string;archived_at?:string;decision?:string;reason?:string;checks:{name:string;passed:boolean;detail:string}[]};
type Data={reviews:Review[];stats:{total:string;pending:string;approved:string;rejected:string};access:{can_edit:boolean;can_review:boolean;actorId:string}};
type Registry={agents:{id:string;archived_at?:string}[];agentVersions:{id:string;agent_id:string;number:number;configuration:{name:string}}[];skillVersions:{id:string;configuration:Record<string,string>;number:number}[];bindings:{agent_version_id:string;skill_version_id:string}[];knowledgeBindings:{agent_version_id:string;document_id:string}[];documents:{id:string;title:string;archived_at?:string}[]};
export default function WorkspaceReviews({children}:{children:ReactNode}){const a=useAccount();if(a.mode==='demo')return <>{children}</>;if(!a.workspaceId||!a.authenticated)return <section className="surfacePage hybridPage registry"><h1>Governance</h1><Link href="/settings">Select a workspace →</Link></section>;return <Reviews key={a.workspaceId} workspaceId={a.workspaceId}/>}
function Reviews({workspaceId}:{workspaceId:string}){
 const [data,setData]=useState<Data>();const [registry,setRegistry]=useState<Registry>();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [page,setPage]=useState(0);const [reload,setReload]=useState(0);const [selected,setSelected]=useState('');const [version,setVersion]=useState('');const [notes,setNotes]=useState('');const [reason,setReason]=useState('');const [decision,setDecision]=useState('approved');const [busy,setBusy]=useState(false);
 useEffect(()=>{const abort=new AbortController();Promise.all([`/api/workspace/reviews?page=${page}`,'/api/workspace/registry'].map(url=>fetch(url,{cache:'no-store',signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);return d}))).then(([d,r])=>{setData(d);setRegistry(r)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort()},[page,reload]);
 async function change(value:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/workspace/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...value,workspaceId})});const d=await r.json();if(!r.ok)throw Error(d.error);setNotice(value.action==='request'?'Review requested. An independent reviewer must decide.':'Decision recorded. This does not authorize production deployment.');setNotes('');setReason('');setReload(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Review unavailable.')}finally{setBusy(false)}}
 const current=data?.reviews.find(r=>r.id===selected);const independent=current&&data?.access.can_review&&current.requested_by!==data.access.actorId&&current.created_by!==data.access.actorId;
 return <section className="surfacePage hybridPage registry"><div className="pageHead"><div><h1>Governance</h1><p>Human review of immutable agent configurations</p></div><button className="button secondary" disabled={busy} onClick={()=>{setError('');setReload(n=>n+1)}}>Refresh</button></div><p className="hybridDataNote">Configuration reviews · Production deployment is not enabled</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}<Metrics items={[["Pending review",data?.stats.pending??'—'],["Configuration approved",data?.stats.approved??'—'],["Rejected",data?.stats.rejected??'—']]}/>
 <div className="knowledgeWorkspace"><article className="panel registryScroll"><h2>Configuration reviews</h2>{data?.access.can_edit&&<details><summary>Request a review</summary><form onSubmit={e=>{e.preventDefault();void change({action:'request',agentVersionId:version,notes})}}><label>Agent version<select required value={version} onChange={e=>setVersion(e.target.value)}><option value="">Select version</option>{registry?.agentVersions.filter(v=>registry.agents.some(a=>a.id===v.agent_id&&!a.archived_at)).sort((a,b)=>b.number-a.number).map(v=><option key={v.id} value={v.id}>{v.configuration.name} · v{v.number}</option>)}</select></label><label>Review notes<textarea required maxLength={1000} value={notes} onChange={e=>setNotes(e.target.value)}/></label><p>A new configuration check must pass before this request can be recorded.</p><button disabled={busy} className="button primary">Submit for review</button></form></details>}<Table caption="Configuration reviews" headers={['Agent','Version','Decision','Requested']} rows={(data?.reviews??[]).map(r=>[<button className="workspaceTextAction" key="name" onClick={()=>{setSelected(r.id);setReason('')}}>{r.configuration.name}</button>,`v${r.number}`,<Status key="status">{r.decision??'Pending'}</Status>,new Date(r.created_at).toLocaleDateString()])} emptyMessage={data?'No configuration reviews requested yet.':'Loading reviews…'}/>
<div className="registryToolbar"><button className="button secondary" disabled={page===0||busy} onClick={()=>{setSelected('');setPage(n=>n-1)}}>Previous</button><span>Page {page+1}</span><button className="button secondary" disabled={!data||(page+1)*25>=Number(data.stats.total)||busy} onClick={()=>{setSelected('');setPage(n=>n+1)}}>Next</button></div></article><aside className="panel"><h2>Review details</h2>{current?<><h3>{current.configuration.name} · v{current.number}</h3><p>{current.notes}</p><details open><summary>Version snapshot</summary>{Object.entries(current.configuration).map(([k,v])=><p key={k}><strong>{k}</strong><br/>{v||'—'}</p>)}</details><details><summary>Pinned skills</summary>{registry?.bindings.filter(b=>b.agent_version_id===current.agent_version_id).map(b=>{const skill=registry.skillVersions.find(v=>v.id===b.skill_version_id);return <div key={b.skill_version_id}><h3>{skill?.configuration.name} · v{skill?.number}</h3><p>{skill?.configuration.instructions}</p></div>})}</details><details><summary>Knowledge sources</summary>{registry?.knowledgeBindings.filter(b=>b.agent_version_id===current.agent_version_id).map(b=>{const d=registry.documents.find(d=>d.id===b.document_id);return <p key={b.document_id}>{d?.title}{d?.archived_at?' · Archived':''}<small>{b.document_id}</small></p>})}<Link href="/knowledge">Read source documents →</Link></details><details><summary>Checks at submission</summary>{current.checks.map(c=><p key={c.name}>{c.passed?'✓':'Needs attention'} · {c.name}<small>{c.detail}</small></p>)}</details>{current.decision?<p><strong>{current.decision}</strong><br/>{current.reason}</p>:current.archived_at?<p>Restore the agent before recording a decision.</p>:independent?<form onSubmit={e=>{e.preventDefault();void change({action:'decide',reviewId:current.id,decision,reason})}}><label>Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="approved">Approve configuration</option><option value="rejected">Reject configuration</option></select></label><label>Reason<textarea required maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button primary" disabled={busy}>Record decision</button></form>:<p>An Org Admin or Reviewer / Approver who did not author or submit this configuration must make the decision.</p>}</>:<p>Select a review to inspect its exact version, references and decision.</p>}</aside></div></section>
}
