'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Metrics,Table,Progress} from './hybrid/UI';
type Case={query:string;expectedDocumentId:string};
type Result=Case&{runId:string;passed:boolean;returnedDocumentIds:string[]};
type Suite={id:string;name:string;agent_name:string;number:number;cases:Case[];archived_at:string|null};
type Run={id:string;name:string;created_at:string;results:Result[]};
type Data={suites:Suite[];runs:Run[];total:number;access:{can_edit:boolean;can_run:boolean}};
type Registry={agents:{id:string;archived_at:string|null}[];agentVersions:{id:string;agent_id:string;number:number;configuration:{name:string}}[];knowledgeBindings:{agent_version_id:string;document_id:string}[];documents:{id:string;title:string;archived_at:string|null}[]};
export default function WorkspaceRetrievalEvaluations({workspaceId,navigation}:{workspaceId:string;navigation?:ReactNode}){
 const [data,setData]=useState<Data>();const [registry,setRegistry]=useState<Registry>();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [reload,setReload]=useState(0);const [page,setPage]=useState(0);const [creating,setCreating]=useState(false);const [name,setName]=useState('');const [version,setVersion]=useState('');const [cases,setCases]=useState<Case[]>([{query:'',expectedDocumentId:''}]);const retry=useRef<{suiteId:string;id:string}|undefined>(undefined);
 useEffect(()=>{const controller=new AbortController();setError('');Promise.all([`/api/workspace/retrieval-evaluations?page=${page}`,'/api/workspace/registry'].map(async url=>{const response=await fetch(url,{signal:controller.signal,cache:'no-store'});const value=await response.json();if(!response.ok)throw Error(value.error);return value})).then(([d,r])=>{setData(d);setRegistry(r)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[reload,page]);
 async function submit(action:'create'|'run',suiteId?:string){setBusy(true);setError('');setNotice('');if(action==='run'&&(!retry.current||retry.current.suiteId!==suiteId))retry.current={suiteId:suiteId!,id:crypto.randomUUID()};try{const response=await fetch('/api/workspace/retrieval-evaluations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,action,name,agentVersionId:version,cases,suiteId,id:retry.current?.id})});const result=await response.json();if(!response.ok)throw Error(result.error);if(action==='create'){setCreating(false);setName('');setCases([{query:'',expectedDocumentId:''}]);setNotice('Suite saved with its exact agent version.')}else{retry.current=undefined;const passed=result.results.filter((r:Result)=>r.passed).length;setNotice(`${passed}/${result.results.length} cases retrieved the expected source in the top 5 results. No production approval is implied.`)}setPage(0);setReload(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Evaluation unavailable.')}finally{setBusy(false)}}
 const versions=registry?.agentVersions.filter(v=>registry.agents.some(a=>a.id===v.agent_id&&!a.archived_at))??[];
 const sources=registry?.documents.filter(d=>!d.archived_at&&registry.knowledgeBindings.some(b=>b.agent_version_id===version&&b.document_id===d.id))??[];
 const title=(id:string)=>registry?.documents.find(d=>d.id===id)?.title??id;
 return <section className="surfacePage hybridPage registry"><div className="pageHead"><div><h1>Evaluations</h1><p>Source retrieval · Tests against a saved agent version</p></div><div className="registryActions"><button className="button secondary" disabled={busy} onClick={()=>setReload(n=>n+1)}>Refresh</button><button className="button primary" disabled={busy||!data?.access.can_edit} onClick={()=>setCreating(v=>!v)}>{creating?'Close editor':'Create test suite'}</button></div></div>{navigation}<p className="hybridDataNote">Source retrieval checks · Behavioral readiness and deployment approval are evaluated separately</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 <Metrics items={[["Test suites",data?String(data.suites.length):'—'],["Recorded runs",data?String(data.total):'—'],["Latest retrieval score",data?.runs[0]?.results.length?`${Math.round(data.runs[0].results.filter(r=>r.passed).length/data.runs[0].results.length*100)}%`:'—'],["Behavioral readiness","—"]]}/>
 {creating&&<form className="panel registryCard" onSubmit={e=>{e.preventDefault();void submit('create')}}><h2>New retrieval suite</h2><div className="registryFields"><label>Suite name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Agent version<select required value={version} onChange={e=>{setVersion(e.target.value);setCases([{query:'',expectedDocumentId:''}])}}><option value="">Select version</option>{versions.map(v=><option key={v.id} value={v.id}>{v.configuration.name} · v{v.number}</option>)}</select></label></div>{cases.map((c,i)=><fieldset key={i}><legend>Case {i+1}</legend><div className="registryFields"><label>Search words<input required maxLength={200} value={c.query} onChange={e=>setCases(cs=>cs.map((x,j)=>j===i?{...x,query:e.target.value}:x))}/></label><label>Expected source<select required value={c.expectedDocumentId} onChange={e=>setCases(cs=>cs.map((x,j)=>j===i?{...x,expectedDocumentId:e.target.value}:x))}><option value="">Select a linked document</option>{sources.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label></div><button className="button secondary" type="button" disabled={cases.length===1||busy} onClick={()=>setCases(cs=>cs.filter((_,j)=>j!==i))}>Remove case</button></fieldset>)}{version&&!sources.length&&<p>Link active knowledge documents to this agent version before creating a suite.</p>}<div className="registryActions"><button className="button secondary" type="button" disabled={cases.length>=10||busy} onClick={()=>setCases(cs=>[...cs,{query:'',expectedDocumentId:''}])}>Add case</button><button className="button primary" disabled={busy||!sources.length}>Save suite</button></div></form>}
 <div className="knowledgeWorkspace"><article className="panel registryScroll"><h2>Saved suites</h2>{!data?<p>Loading…</p>:data.suites.length?data.suites.map(s=><div className="knowledgeRow" key={s.id}><h3>{s.name}</h3><p>{s.agent_name} · v{s.number} · {s.cases.length} cases{s.archived_at?' · Agent archived':''}</p><details><summary>View test cases</summary>{s.cases.map((c,i)=><p key={i}>{c.query} → {title(c.expectedDocumentId)}</p>)}</details><button className="button secondary" disabled={busy||!data.access.can_run||Boolean(s.archived_at)} onClick={()=>void submit('run',s.id)}>{busy?'Please wait…':'Run suite'}</button></div>):<p>No suites yet. Add queries and the documents you expect to retrieve.</p>}</article><aside className="panel registryScroll"><h2>Recorded results</h2>{data?.runs.map(r=><details key={r.id}><summary>{r.name} · {r.results.filter(c=>c.passed).length}/{r.results.length} found · {new Date(r.created_at).toLocaleString()}</summary>{r.results.map((c,i)=><div className="knowledgeRow" key={i}><strong>{c.passed?'Found':'Not found'} · {c.query}</strong><p>Expected: {title(c.expectedDocumentId)}</p><p>Returned: {c.returnedDocumentIds.map(title).join(', ')||'No matches'}</p><small>Source search: {c.runId}</small></div>)}</details>)}{data&&!data.runs.length&&<p>No evaluations recorded yet.</p>}<div className="registryToolbar"><button className="button secondary" disabled={busy||!page} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page+1}</span><button className="button secondary" disabled={busy||!data||(page+1)*25>=data.total} onClick={()=>setPage(n=>n+1)}>Next</button></div></aside></div></section>
}
