'use client';
import {useEffect,useState,type ReactNode,type FormEvent} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useAccount} from './AccountContext';
import {Bot, Puzzle, FileText, Settings2, Activity, Layers, BookOpen, ArrowUpRight} from 'lucide-react';
import {PageTitle,Metrics,Table} from './hybrid/UI';
import './WorkspaceRegistry.css';
import {Tabs} from './journeys/Shared';
import AgentInventoryView from './hybrid/AgentInventoryView';
import WorkspaceSkillPortfolio from './WorkspaceSkillPortfolio';
import AgentBlueprintWizard from './AgentBlueprintWizard';
type Kind='agent'|'skill';
type Resource={id:string;name:string;description:string;revision:number;updated_at:string;archived_at?:string|null};
type Version={id:string;agent_id?:string;skill_id?:string;number:number;configuration:Record<string,string>;created_at:string};
type Data={documents:{id:string;title:string;archived_at?:string|null}[];knowledgeBindings:{agent_version_id:string;document_id:string}[];access:{can_edit:boolean;role:string};agents:Resource[];skills:Resource[];agentVersions:Version[];skillVersions:Version[];bindings:{agent_version_id:string;skill_version_id:string}[];audit:{id:string;resource_id:string;action:string;created_at:string}[]};
export function RegistrySurface({kind,id,children,create=false,templateId}:{kind:Kind;id?:string;children:ReactNode;create?:boolean;templateId?:string}){
 const account=useAccount();
 if(account.mode==='demo')return <>{children}</>;
 if(!account.authenticated||!account.workspaceId)return <section className="surfacePage hybridPage registry"><h1>Select your workspace</h1><p>Sign in and select a workspace to manage your organization’s agents and skills.</p><Link href="/settings">Open Settings →</Link></section>;
 return <WorkspaceRegistry key={`${account.workspaceId}:${kind}:${id??''}:${templateId??''}`} kind={kind} id={id} workspaceId={account.workspaceId} create={create} templateId={templateId}/>;
}
function WorkspaceRegistry({kind,id,workspaceId,create,templateId}:{kind:Kind;id?:string;workspaceId:string;create:boolean;templateId?:string}){
 const router=useRouter();const [data,setData]=useState<Data>();const [error,setError]=useState('');const [editing,setEditing]=useState(create);const [tab,setTab]=useState('Overview');const [query,setQuery]=useState('');const [selected,setSelected]=useState('');const [reload,setReload]=useState(0);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [statusFilter,setStatusFilter]=useState('All');
 useEffect(()=>{const abort=new AbortController();setError('');fetch('/api/workspace/registry',{cache:'no-store',signal:abort.signal}).then(async r=>{const value=await r.json();if(!r.ok)throw new Error(value.error);setData(value)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return ()=>abort.abort()},[reload]);
 async function lifecycle(action:string,sourceVersionId?:string){if(!data||!id)return;const r=(kind==='agent'?data.agents:data.skills).find(r=>r.id===id);if(!r)return;setBusy(true);setError('');try{const response=await fetch('/api/workspace/registry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,kind,id,revision:r.revision,action,sourceVersionId})});const result=await response.json();if(!response.ok)throw Error(result.error);setNotice(action==='restore-version'?'Snapshot saved as a new version. Previous versions are retained.':action==='archive'?'Configuration archived. History is retained.':'Configuration restored.');setSelected('');setReload(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 if(!data)return <section className="surfacePage hybridPage registry"><p role={error?'alert':'status'}>{error||'Loading saved configurations…'}</p>{error&&<button className="button secondary" onClick={()=>setReload(n=>n+1)}>Try again</button>}</section>;
 const resources=kind==='agent'?data.agents:data.skills;const resource=resources.find(r=>r.id===id);const versions=(kind==='agent'?data.agentVersions:data.skillVersions).filter(v=>(kind==='agent'?v.agent_id:v.skill_id)===id).sort((a,b)=>b.number-a.number);const latest=versions[0];const current=versions.find(v=>v.id===selected)??latest;const base=`/${kind}s`;const canEdit=data.access.can_edit;
 if(id&&!resource)return <section className="surfacePage hybridPage registry"><h1>{kind==='agent'?'Agent':'Skill'} unavailable</h1><p>This item is not in the selected workspace.</p><Link href={base}>Back to {kind}s</Link></section>;
 const bound=current?data.bindings.filter(b=>b.agent_version_id===current.id).map(b=>data.skillVersions.find(v=>v.id===b.skill_version_id)).filter((v):v is Version=>!!v):[];
 const visibleResources=resources.filter(r=>statusFilter==='Archived'?!!r.archived_at:statusFilter==='Configured'?!r.archived_at:true).filter(r=>`${r.name} ${r.description}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updated_at.localeCompare(a.updated_at));
 const detailTabs=kind==='agent'?['Overview','Configuration','Knowledge','Tools','Skills','Evaluations','Versions','Activity','AgentOps']:['Overview','Configuration','Tools','Knowledge','Governance','Evaluations','Versions','Usage','Activity'];
 const ResourceIcon=kind==='agent'?Bot:Puzzle;
 const used=kind==='skill'?new Set(data.bindings.filter(b=>data.skillVersions.some(v=>v.id===b.skill_version_id&&v.skill_id===id)).map(b=>data.agentVersions.find(v=>v.id===b.agent_version_id)?.agent_id)).size:0;
 const activeResources=resources.filter(r=>!r.archived_at);
 const latestFor=(resourceId:string)=>(kind==='agent'?data.agentVersions:data.skillVersions).filter(v=>(kind==='agent'?v.agent_id:v.skill_id)===resourceId).sort((a,b)=>b.number-a.number)[0];
 const resourceTable=<article className="registryCollection"><header><h2><ResourceIcon size={17}/>{kind==='agent'?'Agent directory':'Skill library'}</h2><span>{visibleResources.length} results</span></header><div className="registryScroll"><Table caption={`Saved ${kind}s`} headers={['Name','Status','Version',...(kind==='agent'?['Skills','Knowledge','Owner']:['Domain','Agent versions']),'Updated','']} onRowClick={index=>router.push(`${base}/${visibleResources[index].id}`)} rows={visibleResources.map(r=>{const v=latestFor(r.id);return [<Link className="registryResourceLink" key={r.id} href={`${base}/${r.id}`}><span className="workspaceIcon"><ResourceIcon size={19}/></span><span>{r.name}<small>{r.description||'Saved workspace configuration'}</small></span></Link>,<span key="status" className="registryBadge">{r.archived_at?'Archived':'Configured'}</span>,`v${v?.number??0}`,...(kind==='agent'?[String(data.bindings.filter(b=>b.agent_version_id===v?.id).length),String(data.knowledgeBindings.filter(b=>b.agent_version_id===v?.id).length),v?.configuration.businessOwner||'Unassigned']:[v?.configuration.domain||'Unassigned',String(new Set(data.bindings.filter(b=>data.skillVersions.some(s=>s.id===b.skill_version_id&&s.skill_id===r.id)).map(b=>b.agent_version_id)).size)]),new Date(r.updated_at).toLocaleDateString(),<Link key="open" href={`${base}/${r.id}`} aria-label={`Open ${r.name}`}><ArrowUpRight size={17}/></Link>]})} emptyMessage={`No ${kind}s match this view. ${canEdit?'Create a configuration or adjust your filters.':''}`}/></div><footer><span>Versioned configurations · Select a row to open its workspace</span><span>Execution pending activation</span></footer></article>;

 if(kind==='agent'&&!id&&!editing)return <AgentInventoryView description={`${activeResources.length} configured · ${resources.length-activeResources.length} archived`} action={canEdit?<button className="button primary" onClick={()=>router.push('/agents/catalog')}>+ Add Agent</button>:null} search={query} onSearch={setQuery} filter={statusFilter} onFilter={setStatusFilter} filters={['All','Configured','Archived']} note="Workspace data · Configurations saved · Execution not enabled" rows={visibleResources.map(r=>{const v=latestFor(r.id);return {id:r.id,templateId:v?.configuration.templateId,name:r.name,status:r.archived_at?'Archived':'Configured',version:`v${v?.number??0}`,tasks:'—',success:'—',latency:'—',model:v?.configuration.model,owner:v?.configuration.businessOwner||'—',deployed:'—'}})}>{error&&<p role="alert">{error}<button className="button secondary" onClick={()=>setReload(n=>n+1)}>Reload</button></p>}{notice&&<p role="status">{notice}</p>}</AgentInventoryView>;
 if(kind==='skill'&&!id&&!editing)return <WorkspaceSkillPortfolio skills={resources} versions={data.skillVersions} bindings={data.bindings} agentVersions={data.agentVersions} action={canEdit?<button className="button primary" onClick={()=>setEditing(true)}>+ Create Skill</button>:null} feedback={<>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}</>}/>;

 return <section className={`surfacePage hybridPage registry ${editing&&kind==='agent'?'registryAgentCreation':''} ${id?(kind==='agent'?'agentWorkspace':'skillDetailPage'):''}`}>
 {id&&!editing&&<Link href={base}>← {kind==='agent'?'Agents':'Skills'}</Link>}
 {!(editing&&kind==='agent')&&<PageTitle title={resource?.name??(kind==='agent'?'Agents':'Skills')} description={resource?(kind==='agent'?`${current?.configuration.model||'Model not configured'} · Not deployed · Version v${current?.number??'—'}`:`${current?.configuration.domain||'Unassigned'} · v${current?.number??'—'} · ${resource.archived_at?'Archived':'Configured'}`):(kind==='agent'?'Manage your agents, capabilities and configuration lifecycle':'Build and manage reusable capabilities across your agents')}>{canEdit&&!editing&&!resource?.archived_at&&<button className="button primary" onClick={()=>setEditing(true)}>{id?'Create New Version':`+ Create ${kind==='agent'?'Agent':'Skill'}`}</button>}</PageTitle>}
 {error&&<p role="alert">{error} <button className="button secondary" onClick={()=>setReload(n=>n+1)}>Reload</button></p>}{notice&&<p role="status">{notice}</p>}
 {resource?.archived_at&&<p role="status">Archived configuration · History remains available.</p>}{resource&&canEdit&&!editing&&tab==='Configuration'&&<details><summary>Manage configuration</summary><p>Archiving keeps versions and existing references. Restoring makes this configuration available for editing again.</p><button className="button secondary" disabled={busy} onClick={()=>void lifecycle(resource.archived_at?'restore':'archive')}>{resource.archived_at?'Restore configuration':'Archive configuration'}</button></details>}
 {editing?<RegistryEditor templateId={templateId} kind={kind} resource={resource} latest={latest} data={data} workspaceId={workspaceId} onCancel={()=>setEditing(false)} onSaved={(savedId)=>{setEditing(false);setNotice('Configuration saved successfully.');setSelected('');setReload(n=>n+1);if(!id)router.push(`${base}/${savedId}`)}}/>:!id?<>
 <Metrics items={[[kind==='agent'?'Agents configured':'Skills configured',String(activeResources.length),'In this workspace'],['Saved versions',String((kind==='agent'?data.agentVersions:data.skillVersions).length),'Version history retained'],[kind==='agent'?'Skills linked':'Agent version references',String(kind==='agent'?data.bindings.filter(b=>activeResources.some(r=>latestFor(r.id)?.id===b.agent_version_id)).length:data.bindings.filter(b=>data.skillVersions.some(v=>v.id===b.skill_version_id&&activeResources.some(r=>r.id===v.skill_id))).length),'Pinned version bindings'],['Archived',String(resources.length-activeResources.length),'History available']]}/>
 <div className="registryFilterBar"><label>Search {kind}s<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name or description"/></label><div className="registrySegmented" role="group" aria-label="Configuration status">{['All','Configured','Archived'].map(status=><button className="button secondary" key={status} aria-pressed={statusFilter===status} onClick={()=>setStatusFilter(status)}>{status} ({status==='All'?resources.length:status==='Archived'?resources.length-activeResources.length:activeResources.length})</button>)}</div></div>
 {resourceTable}
 </>:<>
 {kind==='skill'&&<Metrics items={[["Agents using",String(used)],["Executions (30d)","—"],["Success rate","—"],["P95 latency","—"],["Avg Cost / Execution","—"]]}/>}
 <section className={kind==='skill'?'skillDetailPanel':'agentDetailPanel'}>
 <Tabs names={detailTabs} current={tab} onChange={setTab}/>
 <div id="journey-panel" role="tabpanel" aria-labelledby={`journey-tab-${detailTabs.indexOf(tab)}`}>
 {tab==='Overview'&&kind==='agent'&&<Metrics items={kind==='agent'?[["Tasks today","—"],["Success rate","—"],["Latency P95","—"],["Cost today","—"]]:[["Saved versions",String(versions.length)],["Agents referencing",String(used)],["Domain",current?.configuration.domain||"Unassigned"],["Execution","Not deployed"]]}/>}
 {tab==='Overview'&&<div className={`hybridSplit ${kind==='agent'?'agentOverviewGrid':'skillOverviewGrid'}`}><article className="panel registryMission">{kind==='agent'?<><h2>Task volume — last 7 days</h2><div className="hybridEmpty"><p>No task executions yet.</p><p>Performance will appear after this agent is deployed.</p></div></>:<><h2>Purpose & instructions</h2><p>{current?.configuration.description||resource?.description}</p><p>{current?.configuration.instructions}</p></>}</article><article className="panel"><h2>{kind==='agent'?'Production configuration':'Configuration'}</h2><dl className="surfaceFacts">{kind==='agent'&&<><div><dt>Infrastructure</dt><dd>{current?.configuration.infrastructure||'Not configured'}</dd></div><div><dt>Model</dt><dd>{current?.configuration.model||'Not configured'}</dd></div></>}{kind==='skill'&&<div><dt>Version</dt><dd>v{current?.number??'—'}</dd></div>}<div><dt>{kind==='agent'?'Skills':'Domain'}</dt><dd>{kind==='agent'?`${bound.length} pinned versions`:current?.configuration.domain||'—'}</dd></div>{kind==='agent'&&<div><dt>Knowledge</dt><dd>{data.knowledgeBindings.filter(b=>b.agent_version_id===current?.id).length} sources</dd></div>}{kind==='agent'&&<><div><dt>Tools</dt><dd>Not connected</dd></div><div><dt>Policies</dt><dd>Not evaluated</dd></div><div><dt>Evaluation score</dt><dd>—</dd></div></>}{kind==='skill'&&<div><dt>Deployment</dt><dd><span className="registryBadge">Not deployed</span></dd></div>}</dl><button className="button secondary" onClick={()=>setTab('Configuration')}>View Configuration →</button></article><article className="panel"><h2><Activity size={17}/> Recent activity</h2>{data.audit.filter(a=>a.resource_id===id).slice(0,5).map(a=><p key={a.id}>{({'created':'Created','version-created':'Version saved','archived':'Archived','restored':'Restored'} as Record<string,string>)[a.action]??a.action}<small>{new Date(a.created_at).toLocaleString()}</small></p>)}<button className="button secondary" onClick={()=>setTab('Activity')}>View all →</button></article></div>}
 {['Tools','Evaluations','AgentOps','Governance'].includes(tab)&&<article className="panel"><h2>{tab}</h2><p>This {kind} has not been deployed. Live {tab.toLowerCase()} data is not available yet.</p><Link href={tab==='Tools'?'/tools':tab==='Evaluations'?'/evaluations':tab==='Governance'?'/governance':'/agentops'}>Open {tab} →</Link></article>}
 {tab==='Configuration'&&<article className="panel registryCard"><h2>Saved configuration · v{current?.number??'—'}</h2><p>This configuration has not been deployed.</p><dl className="surfaceFacts">{Object.entries(current?.configuration??{}).map(([key,value])=><div key={key}><dt>{({businessOwner:'Business owner',targetUsers:'Target users',inputDescription:'Inputs',outputDescription:'Outputs'} as Record<string,string>)[key]??key}</dt><dd>{value||'—'}</dd></div>)}</dl></article>}
 {tab==='Skills'&&<article className="panel registryCard"><h2>Pinned skills · agent v{current?.number??'—'}</h2><p>New skill versions are adopted by saving a new agent version.</p>{bound.length?bound.map(v=><p key={v.id}><Link href={`/skills/${v.skill_id}`}>{v.configuration.name} · v{v.number}</Link></p>):<p>No skills linked to this version.</p>}{canEdit&&!resource?.archived_at&&<button className="button secondary" onClick={()=>setEditing(true)}>Add or update skills</button>} <Link href="/skills">Open Skill Library →</Link></article>}
 {tab==='Usage'&&<article className="panel registryCard"><h2>Agent versions using this skill</h2>{data.bindings.filter(b=>versions.some(v=>v.id===b.skill_version_id)).map(b=>{const a=data.agentVersions.find(v=>v.id===b.agent_version_id);const s=versions.find(v=>v.id===b.skill_version_id);return a?<p key={`${b.agent_version_id}:${b.skill_version_id}`}><Link href={`/agents/${a.agent_id}`}>{a.configuration.name} · agent v{a.number}</Link> · skill v{s?.number}</p>:null})}{!used&&<p>No agents reference this skill yet.</p>}</article>}
 {tab==='Knowledge'&&<article className="panel registryCard"><h2>Knowledge sources · v{current?.number}</h2><p>Documents are pinned to this version. Archived sources are excluded from new searches.</p>{data.knowledgeBindings.filter(b=>b.agent_version_id===current?.id).map(b=>{const d=data.documents.find(d=>d.id===b.document_id);return <p key={b.document_id}>{d?.title??'Document'} {d?.archived_at?'· Archived':''}</p>})}{canEdit&&!resource?.archived_at&&<button className="button secondary" onClick={()=>setEditing(true)}>Update sources</button>}</article>}
 {tab==='Versions'&&<article className="panel registryCard"><h2>Immutable version history</h2><p>Inspect an earlier snapshot without replacing the latest configuration.</p>{versions.map(v=><div className="registryVersion" key={v.id}><span>v{v.number} · {new Date(v.created_at).toLocaleString()}</span><button className="button secondary" onClick={()=>{setSelected(v.id);setTab('Configuration')}}>View snapshot</button>{canEdit&&!resource?.archived_at&&v.id!==latest?.id&&<button className="button secondary" disabled={busy} onClick={()=>void lifecycle('restore-version',v.id)}>Restore as new version</button>}</div>)}</article>}
 {tab==='Activity'&&<article className="panel registryCard"><h2>Recent changes</h2><p>Latest workspace events (up to 50).</p>{data.audit.filter(a=>a.resource_id===id).map(a=><p key={a.id}>{({'created':'Created','version-created':'Version saved','archived':'Archived','restored':'Restored'} as Record<string,string>)[a.action]??a.action} · {new Date(a.created_at).toLocaleString()}</p>)}</article>}
 </div></section></>}
 </section>;
}
export type RegistryEditorProps={kind:Kind;templateId?:string;resource?:Resource;latest?:Version;data:Data;workspaceId:string;onCancel:()=>void;onSaved:(id:string)=>void};
function RegistryEditor(props:RegistryEditorProps){return props.kind==='agent'?<AgentBlueprintWizard {...props}/>:<SkillRegistryEditor {...props}/>;}
function SkillRegistryEditor({kind,resource,latest,workspaceId,onCancel,onSaved}:RegistryEditorProps){
 const [values,setValues]=useState<Record<string,string>>({name:resource?.name??'',description:resource?.description??'',...latest?.configuration});const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const r=await fetch('/api/workspace/registry',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,kind:'skill',id:resource?.id,revision:resource?.revision,name:values.name,description:values.description,configuration:values})});const result=await r.json();if(!r.ok)throw new Error(result.error);onSaved(result.id)}catch(e){setError(e instanceof Error?e.message:'Could not save configuration.')}finally{setBusy(false)}}
 const fields:[string,string,number,boolean][]=[['name','Name',120,true],['description','Description',2000,false],...(kind==='agent'?[['mission','Mission',2000,true],['businessOwner','Business owner',200,false],['targetUsers','Target users',500,false]]:[['domain','Domain',100,true],['instructions','Instructions',8000,true],['inputDescription','Expected inputs',2000,false],['outputDescription','Expected outputs',2000,false]]) as [string,string,number,boolean][]];
 return <form onSubmit={save} className="panel registryCard"><h2>{resource?'Create a new version':`Create ${kind}`}</h2><p>Save a configuration for review. Execution and deployment are separate steps.</p><fieldset disabled={busy}><div className="registryFields">{fields.map(([key,label,max,required])=><label key={key}>{label}{required?' *':''}{max>500?<textarea required={required} maxLength={max} rows={key==='instructions'?6:3} value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}/>:<input required={required} maxLength={max} value={values[key]??''} onChange={e=>setValues({...values,[key]:e.target.value})}/>}</label>)}</div>
 {error&&<p role="alert">{error}</p>}<div className="registryActions"><button className="button secondary" type="button" onClick={onCancel}>Cancel</button><button className="button primary" type="submit">{busy?'Saving…':'Save configuration'}</button></div></fieldset></form>
}
