'use client';
import {useEffect,useState} from 'react';
type Status={checkedAt:string;app:string;database:string;proxy:string;backup:string;backupAt:string|null;freeDiskBytes:number;state:string};
export default function WorkspaceOperationsHealth(){const [status,setStatus]=useState<Status|null>();const [hidden,setHidden]=useState(false);const [error,setError]=useState('');const [reload,setReload]=useState(0);const [busy,setBusy]=useState(true);
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');fetch('/api/platform/operations',{cache:'no-store',signal:controller.signal}).then(async r=>{if(r.status===403){setHidden(true);return}const d=await r.json();if(!r.ok)throw Error(d.error);setHidden(false);setStatus(d.status)}).catch(e=>{if(e.name!=='AbortError'){setStatus(undefined);setError(e.message)}}).finally(()=>{if(!controller.signal.aborted)setBusy(false)});return()=>controller.abort()},[reload]);
 useEffect(()=>{if(hidden)return;const timer=setInterval(()=>setReload(n=>n+1),60000);return()=>clearInterval(timer)},[hidden]);
 if(hidden)return null;
 return <article className="panel registryCard"><div className="registryToolbar"><h2>Platform health</h2><button className="button secondary" disabled={busy} onClick={()=>setReload(n=>n+1)}>Refresh health</button></div>{error&&<p role="alert">{error}</p>}{busy?<p>Checking platform status…</p>:status?<><div className="registryPanels"><div><strong>{status.state==='healthy'?'Checks healthy':'Attention required'}</strong><p>Application: {status.app}<br/>Database: {status.database}<br/>Proxy: {status.proxy}</p></div><div><strong>Local backup: {status.backup}</strong><p>{status.backupAt?new Date(status.backupAt).toLocaleString():'No backup found'}</p><small>Stored on this server. Off-host recovery is not configured.</small></div><div><strong>{(status.freeDiskBytes/1024**3).toFixed(1)} GiB disk available</strong><p>Checked: {new Date(status.checkedAt).toLocaleString()}</p></div></div><p>Checks run every five minutes. This does not verify model behavior or email delivery.</p></>:!error&&<p role="status">Monitoring data is missing or older than 15 minutes. Platform health cannot be confirmed.</p>}</article>
}
