 'use client';
import {useEffect,useState,type ReactNode,type FormEvent} from 'react';
import Link from 'next/link';
import {useAccount} from './AccountContext';
import './WorkspaceRegistry.css';
import {Metrics,Table,IconLabel,Tag,Status} from './hybrid/UI';
import {BookOpen, Activity} from 'lucide-react';
type Doc={id:string;title:string;excerpt:string;body?:string;bytes:number;created_at:string;archived_at?:string};
type Data={documents:Doc[];total:number;page:number;access:{can_edit:boolean};audit:{id:string;action:string;created_at:string}[]};
export default function WorkspaceKnowledge({children}:{children:ReactNode}){
 const account=useAccount();if(account.mode==='demo')return <>{children}</>;
 if(!account.authenticated||!account.workspaceId)return <section className="surfacePage hybridPage registry"><h1>Knowledge</h1><p>Select your workspace to manage documents.</p><Link href="/settings">Open Settings →</Link></section>;
 return <Knowledge key={account.workspaceId} workspaceId={account.workspaceId}/>;
}
function Knowledge({workspaceId}:{workspaceId:string}){
 const [data,setData]=useState<Data>();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [query,setQuery]=useState('');const [search,setSearch]=useState('');const [page,setPage]=useState(0);const [reload,setReload]=useState(0);const [adding,setAdding]=useState(false);const [title,setTitle]=useState('');const [body,setBody]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<Doc>();
 useEffect(()=>{const abort=new AbortController();setError('');fetch(`/api/workspace/knowledge?q=${encodeURIComponent(search)}&page=${page}`,{cache:'no-store',signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort()},[search,page,reload]);
 async function change(value:Record<string,unknown>){setBusy(true);setError('');try{const r=await fetch('/api/workspace/knowledge',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...value,workspaceId})});const d=await r.json();if(!r.ok)throw Error(d.error);setNotice(value.action==='import'?'Document imported and searchable.':'Document archived and excluded from search.');setAdding(false);setSelected(undefined);setTitle('');setBody('');setPage(0);setReload(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Unable to save.')}finally{setBusy(false)}}
 async function open(id:string){setError('');try{const r=await fetch(`/api/workspace/knowledge?id=${id}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setSelected(d.document)}catch(e){setError(e instanceof Error?e.message:'Unable to load.')}}
 return <section className="surfacePage hybridPage registry knowledgePage"><div className="pageHead"><div><h1>Knowledge</h1><p>Enterprise data sources powering your agents</p></div>{data?.access.can_edit&&<button className="button primary" onClick={()=>{setAdding(true);setSelected(undefined)}}>+ Import document</button>}</div>
 {error&&<p role="alert">{error} <button className="button secondary" onClick={()=>setReload(n=>n+1)}>Retry</button></p>}{notice&&<p role="status">{notice}</p>}
 {adding?<form onSubmit={(e:FormEvent)=>{e.preventDefault();void change({action:'import',title,body})}} className="panel knowledgeImport"><h2>Import a document</h2><p>Plain text or Markdown, up to 20 KB. Documents are available to members of this workspace.</p><label>File<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;if(file.size>20000){setError('File exceeds 20 KB.');return}try{setBody(await file.text());setTitle(file.name.slice(0,160));setError('')}catch{setError('Unable to read file.')}}}/></label><label>Title<input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Content<textarea required rows={12} value={body} onChange={e=>setBody(e.target.value)}/></label><div><button className="button secondary" disabled={busy} type="button" onClick={()=>setAdding(false)}>Cancel</button> <button className="button primary" disabled={busy||new TextEncoder().encode(body).length>20000}>{busy?'Importing…':'Import and index'}</button></div></form>:selected?<article className="panel knowledgeImport"><button className="button secondary" onClick={()=>setSelected(undefined)}>← Documents</button><h2>{selected.title}</h2><p>Reference: {selected.id} · {new Date(selected.created_at).toLocaleString()} · {Math.ceil(selected.bytes/1024)} KB</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere',fontFamily:'inherit'}}>{selected.body}</pre>{data?.access.can_edit&&<details><summary>Archive document</summary><p>This removes the document from search. Its content and history are retained.</p><button className="button secondary" disabled={busy} onClick={()=>void change({action:'archive',id:selected.id})}>Confirm archive</button></details>}</article>:<>
 <Metrics items={[["Sources connected","—","External connectors not activated"],["Documents indexed",String(data?.total??'—'),"Workspace documents"],["Index coverage","—","Not measured"],["Sync errors","—","External sync not activated"]]}/>
 <form className="hybridControls" onSubmit={e=>{e.preventDefault();setPage(0);setSearch(query)}}><label className="srOnly" htmlFor="knowledge-search">Search documents</label><input id="knowledge-search" maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search knowledge…"/><button className="button secondary">Search</button><span>{data?.total??'—'} documents</span></form>
 <Table caption="Knowledge sources" headers={['Source','Type','Documents','Last Sync','Status','Agents using','Coverage','Region','View']} rows={(data?.documents??[]).map(d=>[<button className="workspaceTextAction" key="name" onClick={()=>void open(d.id)}><IconLabel kind="source">{d.title}</IconLabel></button>,<Tag key="type">Document</Tag>,1,'—',<Status key="status">Indexed</Status>,'—','—','—',<button className="workspaceTextAction" key="open" onClick={()=>void open(d.id)}>View →</button>])} emptyMessage={data?'No documents found. Import an approved document to start your knowledge base.':'Loading documents…'}/>
 <details className="panel"><summary>Recent knowledge activity</summary>{data?.audit.map(a=><p key={a.id}>Document {a.action}<small>{new Date(a.created_at).toLocaleString()}</small></p>)}{!data?.audit.length&&<p>No imports recorded.</p>}</details>

 <div className="registryToolbar"><button className="button secondary" disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button className="button secondary" disabled={!data||(page+1)*25>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
 </section>;
}
