 'use client';
import {useState,useEffect,type ReactNode} from 'react';
import Link from 'next/link';
import {useAccount} from './AccountContext';
import './WorkspaceRegistry.css';
import {Table,Tag} from './hybrid/UI';
type Event={id:string;actor_id:string;kind:string;resource_id:string;action:string;created_at:string};
export default function WorkspaceAudit({children}:{children:ReactNode}){const account=useAccount();if(account.mode==='demo')return <>{children}</>;if(!account.authenticated||!account.workspaceId)return <section className="surfacePage hybridPage registry"><h1>Audit Log</h1><Link href="/settings">Select a workspace →</Link></section>;return <Audit key={account.workspaceId}/>}
function Audit(){
 const [data,setData]=useState<{events:Event[];total:number}>();const [page,setPage]=useState(0);const [kind,setKind]=useState('all');const [error,setError]=useState('');const [reload,setReload]=useState(0);
 useEffect(()=>{const abort=new AbortController();setError('');setData(undefined);fetch(`/api/workspace/audit?page=${page}&kind=${kind}`,{cache:'no-store',signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort()},[page,kind,reload]);
 function csv(){if(!data)return;const rows=[['Timestamp','Resource type','Resource ID','Action','Actor ID'],...data.events.map(e=>[e.created_at,e.kind,e.resource_id,e.action,e.actor_id])];const url=URL.createObjectURL(new Blob([rows.map(r=>r.map(v=>'"'+v.replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='newneo-audit-page.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 return <section className="surfacePage hybridPage registry"><div className="pageHead"><div><h1>Audit Log</h1><p>Configuration, access and source operations recorded in this workspace</p></div><button className="button secondary" disabled={!data?.events.length} onClick={csv}>Export current page</button></div><div className="registryToolbar"><label>Resource<select value={kind} onChange={e=>{setKind(e.target.value);setPage(0)}}>{['all','agent','skill','knowledge','member','task','check','review','evaluation'].map(k=><option key={k} value={k}>{k==='all'?'All':k}</option>)}</select></label><span>{data?.total??'—'} events</span><button className="button secondary" onClick={()=>setReload(n=>n+1)}>Refresh</button></div>{error&&<p role="alert">{error}</p>}<Table caption="Audit Log" headers={['Timestamp','User','Action','Resource','Resource ID']} rows={(data?.events??[]).map(e=>[<span className="referenceMono" key="time">{new Date(e.created_at).toLocaleString()}</span>,<span className="referenceMono" key="actor">{e.actor_id}</span>,<Tag key="action">{e.action.replaceAll('-',' ')}</Tag>,<Link key="resource" href={e.kind==='evaluation'||e.kind==='check'?'/evaluations':e.kind==='review'?'/governance':e.kind==='task'?'/agentops':e.kind==='member'?'/settings':e.kind==='knowledge'?'/knowledge':`/${e.kind}s/${e.resource_id}`}>{e.kind}</Link>,<span className="referenceMono" key="id">{e.resource_id}</span>])} emptyMessage={data?'No recorded changes yet.':'Loading history…'}/><div className="registryToolbar"><button className="button secondary" disabled={page===0} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page+1}</span><button className="button secondary" disabled={!data||(page+1)*50>=data.total} onClick={()=>setPage(n=>n+1)}>Next</button></div></section>
}
