'use client';
import {useState,type ReactNode} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import SkillInventoryLayout from './hybrid/SkillInventoryLayout';
import {Table,Tag,Status,IconLabel} from './hybrid/UI';
type Skill={id:string;name:string;description:string;updated_at:string;archived_at?:string|null};
type Version={id:string;skill_id?:string;number:number;configuration:Record<string,string>};
export default function WorkspaceSkillPortfolio({skills,versions,bindings,agentVersions,action,feedback}:{skills:Skill[];versions:Version[];bindings:{skill_version_id:string;agent_version_id:string}[];agentVersions:{id:string;agent_id?:string}[];action:ReactNode;feedback:ReactNode}){
 const router=useRouter();const [tab,setTab]=useState('List');const [search,setSearch]=useState('');const [filters,setFilters]=useState<Record<string,string>>({Domain:'All',Maturity:'All',Risk:'All',Status:'All',Owner:'All',Usage:'All'});
 const all=skills.map(skill=>{const history=versions.filter(v=>v.skill_id===skill.id);const latest=[...history].sort((a,b)=>b.number-a.number)[0];const config=latest?.configuration??{};const agents=new Set(bindings.filter(b=>history.some(v=>v.id===b.skill_version_id)).map(b=>agentVersions.find(v=>v.id===b.agent_version_id)?.agent_id).filter(Boolean));return {...skill,latest,domain:config.domain||'Unassigned',maturity:config.maturity||'Not evaluated',risk:config.riskLevel||'Not assessed',owner:config.businessOwner||config.owner||'Unassigned',status:skill.archived_at?'Archived':'Configured',users:agents.size}});
 const options:Record<string,string[]>={Domain:[...new Set(all.map(s=>s.domain))],Maturity:[...new Set(all.map(s=>s.maturity))],Risk:[...new Set(all.map(s=>s.risk))],Status:['Configured','Archived'],Owner:[...new Set(all.map(s=>s.owner))],Usage:['Used by Agents','Not used']};
 const rows=all.filter(s=>`${s.name} ${s.description}`.toLowerCase().includes(search.toLowerCase())&&Object.entries(filters).every(([k,v])=>v==='All'||(k==='Usage'?(v==='Used by Agents'?s.users>0:s.users===0):(({Domain:s.domain,Maturity:s.maturity,Risk:s.risk,Status:s.status,Owner:s.owner} as Record<string,string>)[k]===v))));
 const domains=[...new Set(rows.map(s=>s.domain))];
 const toolbar=<div className="skillFilters portfolioFilters"><label>Search Skills<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Name or capability"/></label>{Object.entries(options).map(([k,values])=><label key={k}>{k}<select value={filters[k]} onChange={e=>setFilters({...filters,[k]:e.target.value})}>{['All',...values].map(v=><option key={v}>{v}</option>)}</select></label>)}</div>;
 return <SkillInventoryLayout action={action} view={tab} onView={setTab} metrics={[["Total Skills",String(skills.length)],["Production Ready","—"],["Proven at Scale","—"],["Reused Across Domains","—"],["Executions (30d)","—"],["Active Agents Using Skills","—"]]}>
 {feedback}
 {tab==='Pipeline'&&toolbar}
 {tab==='List'&&<section className="skillsListPanel" aria-label="Skill inventory"><Table toolbar={toolbar} caption="Organization Skills" headers={['Skill','Maturity','Risk','Status','Agents Using','Executions (30d)','Success Rate','Last Updated','Owner']} rows={rows.map(s=>[<Link key="name" href={`/skills/${s.id}`}><IconLabel kind="skill"><span className="listIdentity"><strong>{s.name}</strong><small>{s.domain} · v{s.latest?.number??0}</small></span></IconLabel></Link>,<Tag key="maturity">{s.maturity}</Tag>,s.risk,<Status key="status">{s.status}</Status>,s.users,'—','—',new Date(s.updated_at).toLocaleDateString('en-US'),s.owner])} onRowClick={i=>router.push(`/skills/${rows[i].id}`)} emptyMessage="No skills match these filters."/></section>}
 {tab==='Pipeline'&&<div className="skillPipeline" aria-label="Skills by configuration stage">{[{name:'Configuration saved',items:rows.filter(s=>!s.archived_at&&!s.users)},{name:'Linked to agents',items:rows.filter(s=>!s.archived_at&&s.users)},{name:'Archived',items:rows.filter(s=>s.archived_at)}].map((lane,i)=><section className={`skillLane lane${i}`} key={lane.name}><header><h2>{lane.name}</h2><span>{lane.items.length} Skills</span></header><div className="skillLaneCards">{lane.items.length?lane.items.map(s=><Link className="pipelineCard" href={`/skills/${s.id}`} key={s.id}><strong>{s.name}</strong><span>{s.domain} · v{s.latest?.number}</span><div><span>{s.users} Agents</span><span>{s.risk}</span></div><div><span>— executions</span><span>— success</span></div><small>{s.status} · {s.owner}</small></Link>):<p className="laneEmpty">No matching Skills</p>}</div></section>)}</div>}
 {tab==='Matrix'&&<section className="panel"><h2>Domain coverage</h2><p>Saved configurations by domain. Production maturity has not been evaluated.</p><Table caption="Skill domain coverage" headers={['Domain','Skills','Linked to agents','Available configurations']} rows={domains.map(domain=>{const items=rows.filter(s=>s.domain===domain);return [domain,items.length,items.filter(s=>s.users).length,<div key={domain}>{items.map(s=><p key={s.id}><Link href={`/skills/${s.id}`}>{s.name} →</Link></p>)}</div>]})} emptyMessage="No skills available."/></section>}
 {tab==='Intelligence'&&<div className="skillOverviewGrid"><section className="panel"><h2>Portfolio coverage</h2><p>{all.length} skills across {new Set(all.map(s=>s.domain)).size} domains.</p></section><section className="panel"><h2>Adoption opportunities</h2><p>{all.filter(s=>!s.archived_at&&!s.users).length} skills have no agent references.</p>{all.filter(s=>!s.archived_at&&!s.users).map(s=><p key={s.id}><Link href={`/skills/${s.id}`}>{s.name} →</Link></p>)}</section><section className="panel"><h2>Evaluation evidence</h2><p>Execution metrics and behavioral evaluations are not available yet.</p></section></div>}
 </SkillInventoryLayout>
}
