'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import Link from 'next/link';
import {useAccount} from './AccountContext';
import {Metrics,PageTitle,Table,Status,IconLabel} from './hybrid/UI';
import {Tabs} from './journeys/Shared';
import './WorkspaceRegistry.css';
import WorkspaceOperationsHealth from './WorkspaceOperationsHealth';
import WorkspaceCostConsole from './WorkspaceCostConsole';
import WorkspaceRetrievalEvaluations from './WorkspaceRetrievalEvaluations';
type Hit={id:string;title:string;excerpt:string};
type Run={id:string;query:string;agent_name:string;number:number;created_at:string;result:Hit[];duration_ms:number};
type Check={id:string;agent_name:string;number:number;created_at:string;checks:{name:string;passed:boolean;detail:string}[]};
type Data={access:{can_run:boolean};total:number;page:number;runs:Run[];checks:Check[];stats:{runs_24h:string;matched_24h:string;avg_search_ms:string|null}};
type Registry={agents:{id:string;archived_at?:string}[];agentVersions:{id:string;agent_id:string;number:number;configuration:{name:string}}[]};
type View='playground'|'operations'|'checks'|'costs'|'reports';
const titles={playground:'Playground',operations:'AgentOps',checks:'Evaluations',costs:'FinOps',reports:'Reports'};
export default function WorkspaceSourceOps({children,view}:{children:ReactNode;view:View}){const a=useAccount();if(a.mode==='demo')return <>{children}</>;if(!a.authenticated||!a.workspaceId)return <section className="surfacePage hybridPage registry"><h1>{titles[view]}</h1><Link href="/settings">Select a workspace →</Link></section>;return view==='costs'?<WorkspaceCostConsole/>:view==='checks'?<EvaluationWorkspace key={a.workspaceId} workspaceId={a.workspaceId}/>:<SourceOps key={a.workspaceId} workspaceId={a.workspaceId} view={view}/>}
function EvaluationWorkspace({workspaceId}:{workspaceId:string}){const [tab,setTab]=useState('Source retrieval');const navigation=<Tabs names={['Source retrieval','Configuration checks']} current={tab} onChange={setTab}/>;return tab==='Source retrieval'?<WorkspaceRetrievalEvaluations workspaceId={workspaceId} navigation={navigation}/>:<SourceOps workspaceId={workspaceId} view="checks" navigation={navigation}/>}

function SourceOps({workspaceId,view,navigation}:{workspaceId:string;view:View;navigation?:ReactNode}){
 const [operationTab,setOperationTab]=useState('Activity');const [data,setData]=useState<Data>();const [registry,setRegistry]=useState<Registry>();const [error,setError]=useState('');const [notice,setNotice]=useState('');const [page,setPage]=useState(0);const [reload,setReload]=useState(0);const [version,setVersion]=useState('');const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<Run>();const pending=useRef<{key:string;id:string}|undefined>(undefined);
 useEffect(()=>{const abort=new AbortController();setError('');Promise.all([fetch(`/api/workspace/runs?page=${page}`,{cache:'no-store',signal:abort.signal}),fetch('/api/workspace/registry',{cache:'no-store',signal:abort.signal})].map(async r=>{const response=await r;const value=await response.json();if(!response.ok)throw Error(value.error);return value})).then(([d,r])=>{setData(d);setRegistry(r)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>abort.abort()},[page,reload]);
 async function run(action:'search'|'check'){setBusy(true);setError('');setNotice('');const key=JSON.stringify([version,query]);if(!pending.current||pending.current.key!==key)pending.current={key,id:crypto.randomUUID()};try{const r=await fetch('/api/workspace/runs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workspaceId,action,id:pending.current.id,agentVersionId:version,query})});const value=await r.json();if(!r.ok)throw Error(value.error);if(action==='search'){setSelected(value);pending.current=undefined;setNotice(value.result.length?'Search completed. Source excerpts are shown below.':'Search completed. No matching words in the linked sources.');}else setNotice('Configuration checks recorded. These do not certify AI behavior or authorize production deployment.');setPage(0);setReload(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Operation unavailable.')}finally{setBusy(false)}}
 const versions=registry?.agentVersions.filter(v=>registry.agents.some(a=>a.id===v.agent_id&&!a.archived_at)).sort((a,b)=>a.configuration.name.localeCompare(b.configuration.name)||b.number-a.number)??[];
 function exportPage(){if(!data)return;const rows=[['Run','Agent','Version','Time','Search','Matches','Search latency ms'],...data.runs.map(r=>[r.id,r.agent_name,String(r.number),r.created_at,r.query,String(r.result.length),String(r.duration_ms)])];const text=rows.map(row=>row.map(v=>'"'+(/^[=+@\-\t\r]/.test(v)?"'":"")+v.replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='newneo-source-runs.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const history=<><Table caption="Source search history" headers={['Search','Agent','Version','Time','Sources','Latency','']} rows={(data?.runs??[]).map(r=>[<button className="workspaceTextAction" onClick={()=>setSelected(r)} key="query">{r.query}</button>,r.agent_name,`v${r.number}`,new Date(r.created_at).toLocaleString(),String(r.result.length),`${r.duration_ms} ms`,<button className="workspaceTextAction" key="open" onClick={()=>setSelected(r)}>View →</button>])} emptyMessage={data?'No document searches recorded. Search linked sources in Playground to begin.':'Loading recorded searches…'}/><div className="registryToolbar"><button className="button secondary" disabled={page===0||busy} onClick={()=>setPage(n=>n-1)}>Previous</button><span>Page {page+1}</span><button className="button secondary" disabled={!data||(page+1)*25>=data.total||busy} onClick={()=>setPage(n=>n+1)}>Next</button></div></>;
 const excerpts=<>{selected?<><p>{selected.query}</p>{selected.result.length?selected.result.map(h=><div className="knowledgeRow" key={h.id}><strong>{h.title}</strong><p>{h.excerpt}</p><small>Source: {h.id}</small></div>):<p>No matching sources. Try words present in the linked documents.</p>}<small>Run: {selected.id}</small></>:<div className="hybridEmpty"><IconLabel kind="source">Source search</IconLabel><p>Search your agent’s linked knowledge to inspect original source excerpts.</p></div>}</>;
 const versionSelect=<label>Agent version<select required value={version} onChange={e=>setVersion(e.target.value)}><option value="">Select a version</option>{versions.map(v=><option key={v.id} value={v.id}>{v.configuration.name} · v{v.number}</option>)}</select></label>;
 return <section className={`surfacePage hybridPage registry ${view==='playground'?'playgroundPage':view==='reports'?'reportsPage':'agentOpsPage'}`}>
 <PageTitle title={titles[view]} description={view==='checks'?'Version-specific configuration checks':view==='playground'?'Test linked knowledge in a controlled workspace':view==='reports'?'Workspace search performance and recorded activity':'Monitor workspace activity and service health'}>{view==='reports'?<button className="button secondary" disabled={!data?.runs.length} onClick={exportPage}>Export CSV · current page</button>:<button className="button secondary" disabled={busy} onClick={()=>setReload(n=>n+1)}>Refresh</button>}</PageTitle>
 {navigation}
 {error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {view!=='playground'&&<Metrics items={[["Searches (24h)",data?.stats.runs_24h??'—'],["With matches (24h)",data?.stats.matched_24h??'—'],["Avg search latency",data?.stats.avg_search_ms==null?'—':`${data.stats.avg_search_ms} ms`],["AI executions",'—','Not enabled']]}/>}
 {view==='operations'&&<Tabs names={['Activity','Health','Incidents']} current={operationTab} onChange={setOperationTab}/>}
 {view==='operations'&&operationTab==='Health'?<WorkspaceOperationsHealth/>:view==='operations'&&operationTab==='Incidents'?<Table caption="Incidents" headers={['Severity','Agent','Incident','Status','Detected']} rows={[]} emptyMessage="Live agent incident monitoring is not connected. No incident count is inferred."/>:view==='playground'?<div className="workspacePlayground"><form className="panel workspaceConversation" onSubmit={e=>{e.preventDefault();void run('search')}}><header className="registryToolbar">{versionSelect}<button type="button" className="button secondary" onClick={()=>{setSelected(undefined);setQuery('');setNotice('')}}>Clear</button></header><div className="workspaceTranscript" aria-live="polite">{excerpts}</div><footer><label><span className="srOnly">Search words</span><input required maxLength={200} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your agent’s knowledge…"/></label><button className="button primary" disabled={busy||!data?.access.can_run}>{busy?'Searching…':'Search sources'}</button></footer></form><aside><section className="panel"><h2>Parameters</h2><dl><div><dt>Execution</dt><dd>Document search</dd></div><div><dt>Output</dt><dd>Original source excerpts</dd></div><div><dt>Model</dt><dd>Not enabled</dd></div></dl></section><section className="intelligenceNote"><strong>Knowledge search</strong><p>Returns text from sources linked to the selected version. Generated answers and external actions are not enabled.</p></section><details className="panel"><summary>Search history</summary>{history}</details></aside></div>:view==='checks'?<div className="knowledgeWorkspace"><form className="panel" onSubmit={e=>{e.preventDefault();void run('check')}}><h2>Check a saved configuration</h2><p>Verify mission, pinned skills and linked documents.</p>{versionSelect}<div className="registryActions"><button className="button primary" disabled={busy||!data?.access.can_run}>{busy?'Checking…':'Run configuration checks'}</button></div></form><article className="panel registryScroll"><h2>Latest checks</h2>{data?.checks.map(c=><details key={c.id}><summary>{c.agent_name} · v{c.number} · {c.checks.filter(x=>x.passed).length}/{c.checks.length}</summary><small>{new Date(c.created_at).toLocaleString()}</small>{c.checks.map(x=><p key={x.name}><Status>{x.passed?'Passed':'Needs review'}</Status> {x.name}<small>{x.detail}</small></p>)}</details>)}{data&&!data.checks.length&&<p>No recorded checks yet.</p>}</article></div>:<><section className="workspaceHistory">{history}</section>{selected&&<section className="panel"><div className="surfaceHeading"><h2>Source excerpts</h2><button className="button secondary" onClick={()=>setSelected(undefined)}>Close</button></div>{excerpts}</section>}</>}
 <p className="hybridDataNote">Workspace source-search records · No generated answers or live agent execution</p>
 </section>
}
