 'use client';
import {useEffect,useState} from 'react';
import {useAccount} from './AccountContext';
import './WorkspaceRegistry.css';
type Member={id:string;display_name:string;role:string;active:boolean;revision:number};
type Data={members:Member[];total:number;page:number;access:{role:string;can_manage_members:boolean}};
import {productRoleOptions,productRoleLabel} from '@/lib/product-access';
export default function WorkspaceMembers(){const a=useAccount();return a.mode!=='demo'&&a.authenticated&&a.workspaceId?<Members key={a.workspaceId} workspaceId={a.workspaceId}/>:null}
function Members({workspaceId}:{workspaceId:string}){
 const [data,setData]=useState<Data>();const [page,setPage]=useState(0);const [reload,setReload]=useState(0);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [edit,setEdit]=useState<Member>();const [reason,setReason]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{const controller=new AbortController();setData(undefined);fetch(`/api/workspace/members?page=${page}`,{cache:'no-store',signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d)}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[page,reload]);
 async function save(){if(!edit)return;setBusy(true);setError('');try{const r=await fetch('/api/workspace/members',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...edit,reason,workspaceId})});const d=await r.json();if(!r.ok)throw Error(d.error);setEdit(undefined);setReason('');setNotice(d.changed?'Member access updated. Changes are recorded in Audit Log.':'No changes to save.');setReload(n=>n+1)}catch(e){setError(e instanceof Error?e.message:'Unable to update member.')}finally{setBusy(false)}}
 return <section className="surfacePage hybridPage registry" aria-label="Workspace members"><div className="registryToolbar"><div><h2>Workspace members</h2><p>Manage access for existing members of this workspace.</p></div><button className="button secondary" disabled={busy} onClick={()=>{setError('');setEdit(undefined);setReload(n=>n+1)}}>Refresh</button></div>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!data?<p>Loading access settings…</p>:!data.access.can_manage_members?<p>Your role: <strong>{data.access.role}</strong>. An Org Admin manages member access.</p>:<>
 {edit?<form className="panel knowledgeImport" onSubmit={e=>{e.preventDefault();void save()}}><h3>Edit access · {edit.display_name}</h3><label>Role<select value={edit.role} onChange={e=>setEdit({...edit,role:e.target.value})}>{!productRoleOptions.some(r=>r.value===edit.role)&&<option value={edit.role}>{edit.role} (legacy)</option>}{productRoleOptions.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label><label><input type="checkbox" checked={edit.active} onChange={e=>setEdit({...edit,active:e.target.checked})}/> Active workspace access</label><label>Reason for change<textarea required maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>Revoked members lose access to this workspace. Keep at least one active Org Admin.</p><button className="button secondary" disabled={busy} type="button" onClick={()=>setEdit(undefined)}>Cancel</button> <button disabled={busy} className="button primary">{busy?'Saving…':'Save access changes'}</button></form>:<div className="registryScroll"><table><thead><tr><th>Member</th><th>Role</th><th>Access</th><th>Action</th></tr></thead><tbody>{data.members.map(m=><tr key={m.id}><td>{m.display_name}</td><td>{productRoleLabel(m.role)}</td><td>{m.active?'Active':'Revoked'}</td><td><button className="button secondary" onClick={()=>{setEdit({...m});setReason('');setNotice('')}}>Edit access</button></td></tr>)}</tbody></table></div>}
 <div className="registryToolbar"><button className="button secondary" disabled={page===0||busy||!!edit} onClick={()=>setPage(n=>n-1)}>Previous</button><span>{data.total} members · Page {page+1}</span><button className="button secondary" disabled={(page+1)*50>=data.total||busy||!!edit} onClick={()=>setPage(n=>n+1)}>Next</button></div></> }</section>
}
