import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {PGlite} from '@electric-sql/pglite';
import {saveRegistry,changeRegistry,readRegistry} from '../server/registry';
import {mutateKnowledge} from '../server/knowledge';
import {runSourceQuery,readSourceRuns,checkConfiguration} from '../server/source-runs';
import {requestConfigurationReview,decideConfigurationReview,readConfigurationReviews} from '../server/configuration-reviews';
import {createRetrievalSuite,runRetrievalEvaluation,readRetrievalEvaluations} from '../server/retrieval-evaluations';
import {readWorkspaceAudit} from '../server/workspace-audit';
test('lifecycle and source execution preserve scope, history, idempotency and source availability',async()=>{
 const db=new PGlite();try{
 await db.exec('CREATE ROLE newneo_app');
 for(const file of ['001_platform.sql','002_identity_and_drafts.sql','005_account_profiles.sql','006_versioned_registry.sql','007_knowledge.sql','008_workspace_members.sql','009_registry_lifecycle.sql','010_source_runs.sql','011_configuration_reviews.sql','012_retrieval_evaluations.sql'])await db.exec(await readFile(new URL('../db/migrations/'+file,import.meta.url),'utf8'));
 await db.exec('GRANT USAGE ON SCHEMA newneo TO newneo_app; GRANT SELECT ON newneo.identities,newneo.workspaces,newneo.workspace_memberships TO newneo_app; GRANT SELECT,INSERT,UPDATE ON newneo.agents,newneo.drafts TO newneo_app');
 const orgs=(await db.query<{id:string}>("INSERT INTO newneo.organizations(name) VALUES('A'),('B') RETURNING id")).rows;
 const ws=async(org:string)=>(await db.query<{id:string}>("INSERT INTO newneo.workspaces(organization_id,name) VALUES($1,'Main') RETURNING id",[org])).rows[0].id;
 const a={organizationId:orgs[0].id,workspaceId:await ws(orgs[0].id)},b={organizationId:orgs[1].id,workspaceId:await ws(orgs[1].id)};
 const users=(await db.query<{id:string}>("INSERT INTO newneo.identities(issuer,subject) VALUES('https://example.test','author'),('https://example.test','reader'),('https://example.test','foreign'),('https://example.test','operator'),('https://example.test','reviewer') RETURNING id")).rows;
 for(const [s,u,role] of [[a,users[0],'Org Admin'],[a,users[1],'Read Only'],[b,users[2],'Org Admin'],[a,users[3],'Operator'],[a,users[4],'Reviewer / Approver']] as const)await db.query('INSERT INTO newneo.workspace_memberships(organization_id,workspace_id,identity_id,can_edit_agents,role) VALUES($1,$2,$3,$4,$5)',[s.organizationId,s.workspaceId,u.id,['AI Engineer','Org Admin'].includes(role),role]);
 await db.exec('SET ROLE newneo_app');
 async function tx<T>(i:number,fn:()=>Promise<T>){await db.exec('BEGIN');try{await db.query("SELECT set_config('newneo.identity_id',$1,true)",[users[i].id]);const v=await fn();await db.exec('COMMIT');return v}catch(e){await db.exec('ROLLBACK');throw e}}
 const author=users[0].id;
 const doc=await tx(0,()=>mutateKnowledge(db,a,author,{action:'import',title:'Approved source',body:'Vacation requests require manager approval.'}));
 const skill=await tx(0,()=>saveRegistry(db,a,author,{kind:'skill',name:'Search documents',configuration:{domain:'Knowledge',instructions:'Return source excerpts.'}}));
 const input={kind:'agent',name:'Document agent',configuration:{mission:'Search approved documents'},skillVersionIds:[skill.versionId],documentIds:[doc.id]};
 const agent=await tx(0,()=>saveRegistry(db,a,author,input));
 const request={id:randomUUID(),agentVersionId:agent.versionId,query:'vacation'};
 const run=await tx(3,()=>runSourceQuery(db,a,users[3].id,request));assert.equal((run.result as unknown[]).length,1);
 const replay=await tx(3,()=>runSourceQuery(db,a,users[3].id,request));assert.equal(replay.replayed,true);
 await assert.rejects(tx(3,()=>runSourceQuery(db,a,users[3].id,{...request,query:'other'})),/already used/);
 await assert.rejects(tx(1,()=>runSourceQuery(db,a,users[1].id,{...request,id:randomUUID()})),/role cannot/);
 await assert.rejects(tx(2,()=>runSourceQuery(db,b,users[2].id,{...request,id:randomUUID()})),/unavailable/);
 await assert.rejects(tx(2,()=>saveRegistry(db,b,users[2].id,input)),/available version/);
 assert.equal((await tx(2,()=>readSourceRuns(db,b))).total,0);
 const checked=await tx(0,()=>checkConfiguration(db,a,author,{agentVersionId:agent.versionId}));assert.equal((checked.checks as {passed:boolean}[]).every(c=>c.passed),true);
 const review=await tx(0,()=>requestConfigurationReview(db,a,author,{agentVersionId:agent.versionId,notes:'Review the approved source search configuration.'}));
 await assert.rejects(tx(0,()=>requestConfigurationReview(db,a,author,{agentVersionId:agent.versionId,notes:'Duplicate'})),/already has a review/);
 await assert.rejects(tx(0,()=>decideConfigurationReview(db,a,author,{reviewId:review.id,decision:'approved',reason:'Own approval'})),/cannot review/);
 await assert.rejects(tx(0,()=>db.query("INSERT INTO newneo.configuration_decisions(organization_id,workspace_id,review_id,actor_id,decision,reason) VALUES($1,$2,$3,$4,'approved','Self approval')",[a.organizationId,a.workspaceId,review.id,author])),/row-level security/);
 await assert.rejects(tx(3,()=>decideConfigurationReview(db,a,users[3].id,{reviewId:review.id,decision:'approved',reason:'Operator'})),/independent reviewer/);
 await assert.rejects(tx(2,()=>decideConfigurationReview(db,b,users[2].id,{reviewId:review.id,decision:'approved',reason:'Foreign'})),/unavailable/);
 await tx(4,()=>decideConfigurationReview(db,a,users[4].id,{reviewId:review.id,decision:'approved',reason:'Configuration reviewed. No production authorization.'}));
 await assert.rejects(tx(4,()=>decideConfigurationReview(db,a,users[4].id,{reviewId:review.id,decision:'rejected',reason:'Changed mind'})),/already recorded/);
 const reviewed=await tx(1,()=>readConfigurationReviews(db,a,users[1].id));assert.equal(Number(reviewed.stats.approved),1);
 await assert.rejects(tx(0,()=>db.query('DELETE FROM newneo.configuration_decisions')),/permission denied/);
 const suiteInput={name:'Find policy sources',agentVersionId:agent.versionId,cases:[{query:'vacation',expectedDocumentId:doc.id},{query:'nonexistentterm',expectedDocumentId:doc.id}]};
 await assert.rejects(tx(3,()=>createRetrievalSuite(db,a,users[3].id,suiteInput)),/role cannot/);
 await assert.rejects(tx(0,()=>createRetrievalSuite(db,a,author,{...suiteInput,cases:[{query:'vacation',expectedDocumentId:randomUUID()}]})),/Every expected/);
 await assert.rejects(tx(0,()=>createRetrievalSuite(db,a,author,{...suiteInput,cases:[suiteInput.cases[0],suiteInput.cases[0]]})),/different query/);
 const suite=await tx(0,()=>createRetrievalSuite(db,a,author,suiteInput));
 const evaluationRequest={id:randomUUID(),suiteId:suite.id};
 await assert.rejects(tx(1,()=>runRetrievalEvaluation(db,a,users[1].id,evaluationRequest)),/role cannot/);
 await assert.rejects(tx(2,()=>runRetrievalEvaluation(db,b,users[2].id,evaluationRequest)),/unavailable/);
 const evaluation=await tx(3,()=>runRetrievalEvaluation(db,a,users[3].id,evaluationRequest));
 assert.deepEqual((evaluation.results as {passed:boolean}[]).map(c=>c.passed),[true,false]);
 assert.equal((await tx(3,()=>runRetrievalEvaluation(db,a,users[3].id,evaluationRequest))).replayed,true);
 await assert.rejects(tx(0,()=>runRetrievalEvaluation(db,a,author,evaluationRequest)),/already used/);
 assert.equal((await tx(1,()=>readRetrievalEvaluations(db,a))).total,1);
 assert.equal((await tx(2,()=>readRetrievalEvaluations(db,b))).total,0);
 await assert.rejects(tx(0,()=>db.query('DELETE FROM newneo.retrieval_evaluations')),/permission denied/);
 await assert.rejects(tx(0,()=>db.query("UPDATE newneo.retrieval_suites SET name='modified'")),/permission denied/);
 assert.equal((await tx(1,()=>readWorkspaceAudit(db,a,new URLSearchParams({kind:'evaluation'})))).total,2);
 const a2=await tx(0,()=>saveRegistry(db,a,author,{...input,id:agent.id,revision:1,name:'Updated agent'}));
 const restored=await tx(0,()=>changeRegistry(db,a,author,{action:'restore-version',kind:'agent',id:agent.id,revision:a2.revision,sourceVersionId:agent.versionId}));assert.equal(restored.number,3);
 const snapshot=await tx(0,()=>readRegistry(db,a));assert.equal((snapshot.knowledgeBindings as unknown[]).length,3);
 await assert.rejects(tx(0,()=>changeRegistry(db,a,author,{action:'archive',kind:'agent',id:agent.id,revision:1})),/changed/);
 await tx(0,()=>changeRegistry(db,a,author,{action:'archive',kind:'agent',id:agent.id,revision:3}));
 await assert.rejects(tx(0,()=>runSourceQuery(db,a,author,{...request,id:randomUUID()})),/unavailable/);
 await assert.rejects(tx(0,()=>saveRegistry(db,a,author,{...input,id:agent.id,revision:4})),/archived/);
 await tx(0,()=>changeRegistry(db,a,author,{action:'restore',kind:'agent',id:agent.id,revision:4}));
 await tx(0,()=>mutateKnowledge(db,a,author,{action:'archive',id:doc.id}));
 await assert.rejects(tx(0,()=>runSourceQuery(db,a,author,{...request,id:randomUUID()})),/no active knowledge/);
 await assert.rejects(tx(0,()=>changeRegistry(db,a,author,{action:'restore-version',kind:'agent',id:agent.id,revision:5,sourceVersionId:agent.versionId})),/available knowledge/);
 await assert.rejects(tx(3,()=>runRetrievalEvaluation(db,a,users[3].id,{id:randomUUID(),suiteId:suite.id})),/no active knowledge/);
 assert.equal((await tx(1,()=>readRetrievalEvaluations(db,a))).total,1);
 const after=await tx(0,()=>readRegistry(db,a));assert.equal((after.agentVersions as unknown[]).length,3);
 const unavailable=await tx(0,()=>checkConfiguration(db,a,author,{agentVersionId:agent.versionId}));assert.equal((unavailable.checks as {name:string;passed:boolean}[]).find(c=>c.name==='Knowledge available')?.passed,false);
 await assert.rejects(tx(3,()=>db.query("UPDATE newneo.source_runs SET query='changed'")),/permission denied/);
 await assert.rejects(tx(0,()=>db.query('DELETE FROM newneo.knowledge_bindings')),/permission denied/);
 const history=await tx(1,()=>readSourceRuns(db,a));assert.equal(history.total,3);assert.equal(history.checks.length,3);assert.equal(history.access.can_run,false);
 const audit=await tx(1,()=>readWorkspaceAudit(db,a,new URLSearchParams({kind:'task'})));assert.equal(audit.total,3);
 }finally{await db.close()}
});
