import type {SqlClient,WorkspaceScope} from './agent-repository';
import {registryAccess,RegistryError} from './registry';
export async function readWorkspaceAudit(db:SqlClient,s:WorkspaceScope,params:URLSearchParams){
 await registryAccess(db,s);const page=Number(params.get('page')??0),kind=params.get('kind')??'all';
 if(!Number.isSafeInteger(page)||page<0||page>10000||!['all','agent','skill','knowledge','member','task','check','review','evaluation'].includes(kind))throw new RegistryError(400,'Invalid audit filter.');
 const union=`SELECT id,actor_id,kind,resource_id,action,created_at FROM newneo.registry_audit WHERE organization_id=$1 AND workspace_id=$2 UNION ALL SELECT id,actor_id,'knowledge' AS kind,document_id AS resource_id,action,created_at FROM newneo.knowledge_audit WHERE organization_id=$1 AND workspace_id=$2 UNION ALL SELECT id,actor_id,'member' AS kind,member_id AS resource_id,action,created_at FROM newneo.membership_audit WHERE organization_id=$1 AND workspace_id=$2 UNION ALL SELECT id,actor_id,'task' AS kind,id AS resource_id,'source-search' AS action,created_at FROM newneo.source_runs WHERE organization_id=$1 AND workspace_id=$2 UNION ALL SELECT id,actor_id,'check' AS kind,id AS resource_id,'configuration-checked' AS action,created_at FROM newneo.configuration_checks WHERE organization_id=$1 AND workspace_id=$2 UNION ALL SELECT id,requested_by AS actor_id,'review' AS kind,id AS resource_id,'review-requested' AS action,created_at FROM newneo.configuration_reviews WHERE organization_id=$1 AND workspace_id=$2 UNION ALL SELECT id,actor_id,'review' AS kind,review_id AS resource_id,decision AS action,created_at FROM newneo.configuration_decisions WHERE organization_id=$1 AND workspace_id=$2 UNION ALL SELECT id,actor_id,'evaluation' AS kind,id AS resource_id,'retrieval-suite-created' AS action,created_at FROM newneo.retrieval_suites WHERE organization_id=$1 AND workspace_id=$2 UNION ALL SELECT id,actor_id,'evaluation' AS kind,suite_id AS resource_id,'retrieval-evaluated' AS action,created_at FROM newneo.retrieval_evaluations WHERE organization_id=$1 AND workspace_id=$2`;
 const args=[s.organizationId,s.workspaceId,kind];const total=Number((await db.query(`SELECT count(*) AS count FROM (${union}) events WHERE ($3='all' OR kind=$3)`,args)).rows[0].count);
 const events=(await db.query(`SELECT * FROM (${union}) events WHERE ($3='all' OR kind=$3) ORDER BY created_at DESC,id DESC LIMIT 50 OFFSET $4`,[...args,page*50])).rows;
 return {events,total,page};
}
