export const corePages={
'ai-infrastructure':{eyebrow:'AI INFRASTRUCTURE READINESS',title:'Use the infrastructure your AI workload actually needs.',lead:'We assess networking, storage, connectivity, security and data center readiness against the execution model — without assuming every customer needs a local AI fabric.',items:[['Assess what already exists','Understand current network, storage, security, cloud connectivity and data center capabilities before designing anything new.'],['Match infrastructure to the execution model','Cloud AI, Compute Starter, Private AI Cluster and Hybrid each require a different infrastructure profile.'],['Upgrade only where the workload requires it','Reuse what already works and add specialized networking, storage or resilience only when the workload justifies it.'],['Validate production readiness','Confirm connectivity, security, resilience, observability and operational dependencies before production.']]},
'ai-compute':{eyebrow:'AI COMPUTE & RUNTIME STRATEGY',title:'Choose where and how enterprise AI should run.',lead:'Cloud, Compute Starter, Private AI Cluster or Hybrid — selected according to privacy, performance, scale, cost and control.',items:[['Cloud AI','Use managed models and cloud AI services when local GPU infrastructure is unnecessary.'],['Compute Starter','Deploy limited local compute for inference, POCs, private workloads or an initial enterprise AI environment.'],['Private AI Cluster','Build dedicated GPU infrastructure when scale, privacy, performance or control requires it.'],['Hybrid AI','Combine private and cloud execution with explicit workload placement, governance and a common operating model.']]},
'agent-factory':{eyebrow:'NEWNEO AI PLATFORM',title:'Build an agent. Expand its skills.',lead:'Configure an agent with a business mission, then add reusable skills through reviewed versions. Knowledge provides context; tools enable actions; skills define the work the agent can accomplish.',items:[['Know','RAG and enterprise knowledge give agents trusted context.'],['Act','MCP, APIs and tools let agents execute governed actions.'],['Control','Identity, policy, approvals and evaluation keep behavior bounded.'],['Improve','AgentOps measures quality, cost, security and reliability after launch.']]},
'agentops':{eyebrow:'AGENTOPS',title:'Keep enterprise AI reliable after it goes live.',lead:'Operate production agents with measurable quality, cost, security, reliability and continuous improvement.',items:[['Quality','Know whether the agent completes the business task correctly.'],['Reliability','Track latency, errors, dependencies and workflow failures.'],['Security','Trace permissions, actions, approvals and policy events.'],['Economics','Measure model and infrastructure cost against the business task.']]},
'rag':{eyebrow:'RAG & ENTERPRISE KNOWLEDGE',title:'Give AI access to the knowledge your business already has.',lead:'Enterprise RAG systems that let AI use trusted company information without retraining the model.',items:[['Connect enterprise data','Documents, wikis, databases and governed knowledge sources.'],['Prepare the knowledge layer','Clean, chunk, enrich and organize content for retrieval.'],['Retrieve the right context','Semantic, hybrid and filtered retrieval designed around the task.'],['Measure answer quality','Evaluate relevance, groundedness and retrieval failures continuously.']]},
'mcp':{eyebrow:'MCP & ENTERPRISE ACTIONS',title:'Let AI do work inside your enterprise systems.',lead:'Connect agents to tools, APIs and business systems so they can take governed actions, not just generate answers.',items:[['Expose safe tools','Give agents explicit, bounded capabilities through APIs and tools.'],['Connect enterprise systems','CRM, ERP, ITSM, Microsoft 365 and custom applications.'],['Enforce permissions','Apply identity, least privilege and approval requirements.'],['Trace every action','Observe tool calls, outcomes, failures and downstream effects.']]},
'ai-security':{eyebrow:'AI SECURITY',title:'Make enterprise AI powerful without losing control.',lead:'Security and governance across identity, data access, tools, models and agent actions.',items:[['Identity','Know which user, agent or service is acting.'],['Data permissions','Control what information can enter context and outputs.'],['Tool boundaries','Limit which actions an agent can execute and when approval is required.'],['Audit and policy','Keep model interactions and agent behavior visible in production.']]},
'private-hybrid-ai':{eyebrow:'PRIVATE & HYBRID AI',title:'Run AI where your business needs it to run.',lead:'Private and hybrid architectures across data center, private cloud and public cloud.',items:[['Privacy','Keep sensitive workloads inside controlled enterprise environments.'],['Performance','Place compute close to data and latency-sensitive workloads.'],['Economics','Balance owned GPU capacity and cloud consumption.'],['Flexibility','Use common operational patterns across multiple execution environments.']]}
} as const;
export type CoreSlug=keyof typeof corePages;