export const corePages={
'ai-infrastructure':{eyebrow:'AI INFRASTRUCTURE',title:'Build the foundation enterprise AI depends on.',lead:'Networking, storage, connectivity and data center foundations designed around AI workloads.',items:[['Prepare the AI network','High-performance networking for GPU clusters and east-west traffic.'],['Modernize the data center','Extend what already works and change only what the workload requires.'],['Connect sites and environments','Secure connectivity across data center, cloud and distributed AI environments.'],['Engineer for production','Resilience, segmentation and observability from the start.']]},
'ai-compute':{eyebrow:'AI COMPUTE',title:'Run enterprise AI on infrastructure built for the workload.',lead:'GPU compute, orchestration and runtime environments for training, fine-tuning and inference.',items:[['Run models in production','Controlled inference environments with the capacity and latency the application needs.'],['Train or fine-tune models','GPU environments for domain adaptation and model development.'],['Keep AI under your control','Private compute for sensitive workloads and enterprise governance.'],['Use the right environment','Hybrid execution without locking the architecture to one model.']]},
'agent-factory':{eyebrow:'AGENT FACTORY',title:'Turn business processes into production AI agents.',lead:'We combine enterprise knowledge, tools, governance and evaluation into agents designed around real work.',items:[['Know','RAG and enterprise knowledge give agents trusted context.'],['Act','MCP, APIs and tools let agents execute governed actions.'],['Control','Identity, policy, approvals and evaluation keep behavior bounded.'],['Improve','AgentOps measures quality, cost, security and reliability after launch.']]},
'agentops':{eyebrow:'AGENTOPS',title:'Keep enterprise AI reliable after it goes live.',lead:'Operate production agents with measurable quality, cost, security, reliability and continuous improvement.',items:[['Quality','Know whether the agent completes the business task correctly.'],['Reliability','Track latency, errors, dependencies and workflow failures.'],['Security','Trace permissions, actions, approvals and policy events.'],['Economics','Measure model and infrastructure cost against the business task.']]},
'rag':{eyebrow:'RAG & ENTERPRISE KNOWLEDGE',title:'Give AI access to the knowledge your business already has.',lead:'Enterprise RAG systems that let AI use trusted company information without retraining the model.',items:[['Connect enterprise data','Documents, wikis, databases and governed knowledge sources.'],['Prepare the knowledge layer','Clean, chunk, enrich and organize content for retrieval.'],['Retrieve the right context','Semantic, hybrid and filtered retrieval designed around the task.'],['Measure answer quality','Evaluate relevance, groundedness and retrieval failures continuously.']]},
'mcp':{eyebrow:'MCP & ENTERPRISE ACTIONS',title:'Let AI do work inside your enterprise systems.',lead:'Connect agents to tools, APIs and business systems so they can take governed actions, not just generate answers.',items:[['Expose safe tools','Give agents explicit, bounded capabilities through APIs and tools.'],['Connect enterprise systems','CRM, ERP, ITSM, Microsoft 365 and custom applications.'],['Enforce permissions','Apply identity, least privilege and approval requirements.'],['Trace every action','Observe tool calls, outcomes, failures and downstream effects.']]},
'ai-security':{eyebrow:'AI SECURITY',title:'Make enterprise AI powerful without losing control.',lead:'Security and governance across identity, data access, tools, models and agent actions.',items:[['Identity','Know which user, agent or service is acting.'],['Data permissions','Control what information can enter context and outputs.'],['Tool boundaries','Limit which actions an agent can execute and when approval is required.'],['Audit and policy','Keep model interactions and agent behavior visible in production.']]},
'private-hybrid-ai':{eyebrow:'PRIVATE & HYBRID AI',title:'Run AI where your business needs it to run.',lead:'Private and hybrid architectures across data center, private cloud and public cloud.',items:[['Privacy','Keep sensitive workloads inside controlled enterprise environments.'],['Performance','Place compute close to data and latency-sensitive workloads.'],['Economics','Balance owned GPU capacity and cloud consumption.'],['Flexibility','Use common operational patterns across multiple execution environments.']]}
} as const;
export type CoreSlug=keyof typeof corePages;