// Provider-neutral business blueprints. Recommendations never grant runtime access.
export type Recommendation={id:string;name:string;reason:string;aliases?:string[];optional?:boolean;highRisk?:boolean};
export type ModelProfile={reasoning:'high'|'medium';latency:'fast'|'standard';costSensitivity:'high'|'medium'|'low';toolUse:'high'|'medium';contextRequirement:'long'|'medium';multimodal:boolean;private?:boolean};
export type Blueprint={defaultMission:string;defaultTargetUsers:string;suggestedBusinessOwner:string;defaultSuccessMetrics:string[];defaultCriticality:string;recommendedSkills:Recommendation[];recommendedKnowledgeTypes:Recommendation[];recommendedTools:Recommendation[];recommendedInfrastructure:string;infrastructureReason:string;recommendedModelProfile:ModelProfile;recommendedGovernancePolicies:Recommendation[];recommendedEvaluationSuite:Recommendation[];recommendedDeploymentPath:string[];expectedTaskProfile:string;expectedRiskProfile:string};
type Seed={id:string;name:string;objective:string;targetUsers:string;categories:string[];complexity?:string};
const rec=(names:string[],reason:string,prefix:string):Recommendation[]=>names.map((name,index)=>({id:`${prefix}-${index}`,name,reason}));
const patterns:Record<string,{owner:string;skills:string[];knowledge:string[];tools:string[];metrics:string[];evaluations:string[];task:string;profile:ModelProfile}>={
 IT:{owner:'IT Operations',skills:['Search IT Knowledge','Create ServiceNow Ticket','Classify IT Request','Escalate Request'],knowledge:['ServiceNow KB','Confluence IT Knowledge','SharePoint IT Documentation'],tools:['Create ServiceNow Ticket','Search ITSM Records','Send Teams Message'],metrics:['Autonomous resolution rate','First-response time','Ticket deflection','Successful tool execution'],evaluations:['Request classification','Knowledge accuracy','Escalation','Tool execution','Permission handling','High-risk action approval'],task:'Resolve and escalate employee IT requests',profile:{reasoning:'high',latency:'fast',costSensitivity:'medium',toolUse:'high',contextRequirement:'medium',multimodal:false}},
 'Customer Service':{owner:'Customer Operations',skills:['Search Product Knowledge','Classify Customer Request','Resolve Customer Question','Escalate Request'],knowledge:['Product Documentation','Customer Support FAQ','Service Policies'],tools:['Search Customer Records','Create Support Ticket','Send Customer Reply'],metrics:['Resolution rate','Customer satisfaction','First-response time','Escalation accuracy'],evaluations:['Answer relevance','Conversation quality','Escalation','Sensitive data handling','Customer identity checks'],task:'Answer customer questions and escalate exceptions',profile:{reasoning:'medium',latency:'fast',costSensitivity:'high',toolUse:'high',contextRequirement:'medium',multimodal:false}},
 Research:{owner:'Research Operations',skills:['Search Enterprise Knowledge','Review Documents','Generate Executive Summary'],knowledge:['Research Documents','Approved Reference Library','SharePoint Research'],tools:['Search Documents','Retrieve References'],metrics:['Citation accuracy','Synthesis quality','Time to insight'],evaluations:['Citation grounding','Document reasoning','Long-context synthesis','Conflicting evidence'],task:'Synthesize long documents with grounded citations',profile:{reasoning:'high',latency:'standard',costSensitivity:'low',toolUse:'medium',contextRequirement:'long',multimodal:false}},
 Finance:{owner:'Finance Operations',skills:['Review Financial Documents','Classify Exceptions','Escalate for Approval'],knowledge:['Finance Policies','Financial Documents','Approval Matrix'],tools:['Search Financial Records','Create Review Request'],metrics:['Exception detection quality','Review turnaround','Approval compliance'],evaluations:['Document accuracy','Exception handling','Permission boundaries','Approval escalation'],task:'Review sensitive financial documents and route exceptions',profile:{reasoning:'high',latency:'standard',costSensitivity:'medium',toolUse:'high',contextRequirement:'long',multimodal:true}},
 HR:{owner:'People Operations',skills:['Search HR Policies','Classify Employee Request','Escalate Request'],knowledge:['Employee Handbook','HR Policies','Onboarding Documentation'],tools:['Search HR Knowledge','Create HR Request'],metrics:['Answer accuracy','Response time','Appropriate escalation'],evaluations:['Policy grounding','Personal data handling','Access separation','Escalation'],task:'Assist employees using approved people policies',profile:{reasoning:'high',latency:'fast',costSensitivity:'medium',toolUse:'medium',contextRequirement:'medium',multimodal:false}},
 Sales:{owner:'Sales Operations',skills:['Search CRM Records','Qualify Opportunity','Summarize Opportunity'],knowledge:['Sales Playbook','Product Documentation','Approved Sales Content'],tools:['Search CRM Records','Create Follow-up Task'],metrics:['CRM retrieval accuracy','Qualification quality','Follow-up completion'],evaluations:['CRM grounding','Qualification criteria','Tool permission checks','Follow-up accuracy'],task:'Support opportunity qualification and structured CRM actions',profile:{reasoning:'high',latency:'fast',costSensitivity:'medium',toolUse:'high',contextRequirement:'medium',multimodal:false}},
 Marketing:{owner:'Marketing Operations',skills:['Review Brand Content','Summarize Campaign Performance','Escalate Content Review'],knowledge:['Brand Guidelines','Campaign Reports','Approved Content'],tools:['Search Campaign Reports','Create Content Review'],metrics:['Brand compliance','Evidence accuracy','Review turnaround'],evaluations:['Brand alignment','Claim grounding','Content policy checks','Review escalation'],task:'Review brand content and synthesize campaign evidence',profile:{reasoning:'high',latency:'standard',costSensitivity:'medium',toolUse:'medium',contextRequirement:'long',multimodal:true}},
 Operations:{owner:'Operations',skills:['Classify Work Request','Search Operating Procedures','Escalate Request'],knowledge:['Operating Procedures','Runbook Documentation','Approval Matrix'],tools:['Search Operational Records','Create Work Request'],metrics:['Task completion rate','Successful tool execution','Exception escalation'],evaluations:['Structured outputs','Tool execution','Failure recovery','Approval routing'],task:'Execute structured, approved operational workflows',profile:{reasoning:'high',latency:'fast',costSensitivity:'medium',toolUse:'high',contextRequirement:'medium',multimodal:false}},
};
export function inferBlueprintCategory(mission:string){
 const text=mission.toLowerCase();
 if(/\b(it|itsm|incident|password|support ticket|senha|chamado)\b/.test(text))return 'IT';
 if(/\b(finance|financial|invoice|payment|financeiro|fatura)\b/.test(text))return 'Finance';
 if(/\b(hr|employee|hiring|recursos humanos|funcionário)\b/.test(text))return 'HR';
 if(/\b(sales|crm|opportunity|vendas)\b/.test(text))return 'Sales';
 if(/\b(marketing|campaign|brand|campanha)\b/.test(text))return 'Marketing';
 if(/\b(research|document|documents|knowledge|pesquisa|documentos|conhecimento)\b/.test(text))return 'Research';
 if(/\b(customer|support|cliente|atendimento)\b/.test(text))return 'Customer Service';
 return 'Operations';
}
export function buildBlueprint(seed:Seed):Blueprint{
 const category=seed.id==='custom'?inferBlueprintCategory(seed.objective):['research-assistant','knowledge-assistant'].includes(seed.id)?'Research':seed.categories[0]||'Operations';
 const p=patterns[category]??patterns.Operations;const sensitive=['Finance','HR'].includes(category)||seed.id==='access-requests';
 const why=`Recommended for this template: ${p.task.toLowerCase()}.`;
 const skills=rec(p.skills,why,'skill');
 if(category==='IT')skills.push(...rec(['Reset Password','Unlock User','Provision User Access'],'Optional advanced capability; requires approval and permission review.','advanced-skill').map(r=>({...r,optional:true,highRisk:true})));
 const knowledge=rec(p.knowledge,'Ground answers in approved organizational sources.','knowledge');
 if(category==='IT')knowledge.push(...rec(['Google Drive','Notion'],'Optional supporting documentation.','optional-knowledge').map(r=>({...r,optional:true})));
 const tools=rec(p.tools,why,'tool');
 if(category==='IT')tools.push(...rec(['Reset Password','Provision User Access','Execute IT Runbook'],'High-risk action: configure human approval before enabling.','advanced-tool').map(r=>({...r,optional:true,highRisk:true})));
 return {defaultMission:seed.id==='it-support'?'Resolve common IT requests, troubleshoot employee issues and automate approved support actions.':seed.objective,defaultTargetUsers:seed.targetUsers,suggestedBusinessOwner:p.owner,defaultSuccessMetrics:p.metrics,defaultCriticality:seed.complexity??(sensitive?'High':'Medium'),recommendedSkills:skills,recommendedKnowledgeTypes:knowledge,recommendedTools:tools,recommendedInfrastructure:sensitive?'Private Cloud':'Cloud',infrastructureReason:sensitive?'Suggested for sensitive data and controlled access. Confirm residency, organization policy and workload before provisioning.':'Suggested for managed operations and fast provisioning. Confirm data boundaries, integrations and workload before deployment.',recommendedModelProfile:p.profile,recommendedGovernancePolicies:rec(['Audit Logging','PII Protection','Role-Based Access Control','Human Approval for High-Risk Actions','Retention Policy — 90 days','Data Residency Review'],'Recommended control in the blueprint; runtime enforcement requires validation.','policy'),recommendedEvaluationSuite:rec([...p.evaluations,'Hallucination resistance','Prompt injection resistance'],'Recommended scenario; execution requires a validated runtime.','evaluation'),recommendedDeploymentPath:['Development','Staging','Production approval'],expectedTaskProfile:p.task,expectedRiskProfile:sensitive?'Sensitive data; mandatory approval review':'Scoped actions; human approval for high-risk requests'};
}
export const modelPreferences=['Balanced','Best Quality','Lowest Cost','Fastest Response','Private / Controlled'] as const;
export type ModelPreference=typeof modelPreferences[number];
export function preferredProfile(base:ModelProfile,preference:string):ModelProfile{
 return {...base,...(preference==='Best Quality'?{reasoning:'high' as const,costSensitivity:'low' as const}:preference==='Lowest Cost'?{costSensitivity:'high' as const}:preference==='Fastest Response'?{latency:'fast' as const}:preference==='Private / Controlled'?{private:true}: {})};
}
export function profileLabel(profile:ModelProfile){return profile.private?'Private / controlled model':profile.contextRequirement==='long'?'Long-context reasoning model':profile.reasoning==='medium'?'Fast conversational model':'Reliable tool-use model'}
export type ModelCandidate={id:string;name:string;provider:string;approved:boolean;available:boolean;profile:ModelProfile;quality:string;latency:string;cost:string;context:string;multimodal:string;toolUse:string};
// Only verified, organization-approved candidates can become a concrete default.
export function rankModels(catalog:ModelCandidate[],profile:ModelProfile){
 return catalog.filter(m=>m.approved&&m.available&&(!profile.private||m.profile.private)&&(!profile.multimodal||m.profile.multimodal)&&!(profile.contextRequirement==='long'&&m.profile.contextRequirement!=='long')).sort((a,b)=>{
 const score=(m:ModelCandidate)=>Number(m.profile.reasoning===profile.reasoning)*3+Number(m.profile.toolUse===profile.toolUse)*3+Number(m.profile.costSensitivity===profile.costSensitivity)*2+Number(m.profile.latency===profile.latency)*2;
 return score(b)-score(a)||a.name.localeCompare(b.name);
 });
}
export function matchRecommendation(name:string,recommendation:Recommendation){const normalize=(v:string)=>v.toLocaleLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,' ').trim();return [recommendation.name,...(recommendation.aliases??[])].some(alias=>normalize(name)===normalize(alias))}
