// Display fixtures transcribed from approved Hybrid supporting frames.
export const hybridAgents = [
  {
    id: 'customer-service',
    name: 'Customer Service Agent',
    status: 'Live',
    tasks: '1,243',
    success: '96%',
    latency: '1.2s',
    model: 'Azure OpenAI GPT-4o',
    cost: 682,
    budget: 800,
    score: 94,
  },
  {
    id: 'it-support',
    name: 'IT Support Agent',
    status: 'Live',
    tasks: '412',
    success: '99%',
    latency: '0.9s',
    model: 'Managed AI · GPT-4o',
    cost: 247,
    budget: 400,
    score: 99,
  },
  {
    id: 'knowledge-assistant',
    name: 'Knowledge Assistant',
    status: 'Live',
    tasks: '3,871',
    success: '94%',
    latency: '0.6s',
    model: 'Claude 3.5',
    cost: 541,
    budget: 600,
    score: 88,
  },
  {
    id: 'sales-assistant',
    name: 'Sales Assistant',
    status: 'Degraded',
    tasks: '287',
    success: '81%',
    latency: '4.2s',
    model: 'Customer Cloud · GPT-4o',
    cost: 348,
    budget: 300,
    score: 72,
  },
  {
    id: 'process-automation',
    name: 'Process Automation',
    status: 'Live',
    tasks: '1,099',
    success: '97%',
    latency: '1.8s',
    model: 'Hybrid AI',
    cost: 389,
    budget: 500,
    score: 96,
  },
  {
    id: 'research-assistant',
    name: 'Research Assistant',
    status: 'Staging',
    tasks: '—',
    success: '—',
    latency: '1.1s',
    model: 'Private AI · Llama 3',
    cost: 83,
    budget: 200,
    score: 87,
  },
];
export const sourceRows = [
  [
    'confluence',
    'Confluence',
    'Wiki',
    '8,247',
    '2 min ago',
    'Live',
    'Customer, Knowledge',
    '94%',
  ],
  [
    'sharepoint',
    'SharePoint',
    'Document',
    '12,403',
    '18 min ago',
    'Live',
    'Process, Knowledge',
    '88%',
  ],
  [
    'zendesk',
    'Zendesk',
    'Tickets',
    '34,218',
    '5 min ago',
    'Live',
    'Customer Service',
    '100%',
  ],
  ['notion', 'Notion', 'Wiki', '2,109', '1 hr ago', 'Live', 'Research', '79%'],
  [
    'salesforce',
    'Salesforce',
    'CRM',
    '9,870',
    'Syncing…',
    'Syncing',
    'Sales',
    '61%',
  ],
  [
    'google-drive',
    'Google Drive',
    'Document',
    '—',
    'Never',
    'Error',
    'None',
    '0%',
  ],
  [
    'servicenow',
    'ServiceNow',
    'ITSM',
    '5,621',
    '34 min ago',
    'Live',
    'IT Support',
    '92%',
  ],
];
export const actionRows = [
  [
    'servicenow',
    'Create ServiceNow Ticket',
    'ServiceNow',
    'Write',
    'Low',
    '3',
    'Active',
  ],
  [
    'confluence',
    'Search Knowledge Base',
    'Confluence',
    'Read',
    'Low',
    '5',
    'Active',
  ],
  [
    'salesforce',
    'Update Salesforce Record',
    'Salesforce',
    'Write',
    'Medium',
    '1',
    'Active',
  ],
  ['teams', 'Send Teams Message', 'Teams', 'Write', 'Low', '4', 'Active'],
  [
    'access',
    'Provision User Access',
    'Okta / AD',
    'Admin',
    'High',
    '1',
    'Restricted',
  ],
  [
    'runbook',
    'Execute IT Runbook',
    'ServiceNow',
    'Execute',
    'Medium',
    '1',
    'Active',
  ],
  ['sap', 'Trigger SAP Workflow', 'SAP', 'Execute', 'High', '0', 'Pending'],
];
export const activity = [
  'Customer Service Agent v2.4 deployed to Production',
  'Sales Assistant latency degraded — P95 now 4.2s',
  'Knowledge Assistant evaluation — 94% readiness',
  'Process Automation Agent v1.1 → Staging',
  'PII policy updated — applied to 6 agents',
];
export const auditRows = [
  [
    '14:35:02',
    'j.silva',
    'Admin',
    'deploy',
    'Customer Service Agent v2.4',
    'Production',
    'Success',
  ],
  [
    '14:30:00',
    'system',
    'System',
    'incident.open',
    'Sales Assistant — High latency',
    'Production',
    'Info',
  ],
  [
    '13:55:00',
    'a.costa',
    'Engineer',
    'policy.edit',
    'PII Data Protection',
    'Global',
    'Success',
  ],
  [
    '12:04:00',
    'j.silva',
    'Admin',
    'deploy',
    'Customer Service Agent v2.3',
    'Production',
    'Rollback',
  ],
  [
    '11:30:00',
    'r.lima',
    'Analyst',
    'eval.run',
    'Knowledge Assistant — RAG Suite',
    'Staging',
    'Success',
  ],
];
