// Approved Hybrid v4 reference catalog. These are design fixtures, not a live provider catalog.
export const hybridModels = [
  {
    id: 'acme-cloud-gpt4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    tag: 'Recommended',
    context: '128K',
    profile: 'Reasoning · Vision · Tools',
    strengths: 'Reasoning · Coding · Vision · Function calling',
    cost: 'Medium',
    latency: 'Fast',
    multimodal: 'Text and images',
  },
  {
    id: 'demo-cloud-claude',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    tag: 'Strong reasoning',
    context: '200K',
    profile: 'Long context · Safety · Writing',
    strengths: 'Long context · Safety · Writing',
    cost: 'Medium',
    latency: 'Fast',
    multimodal: 'Text and images',
  },
  {
    id: 'demo-cloud-gemini',
    name: 'Gemini 1.5 Pro',
    provider: 'Google',
    tag: 'Largest context',
    context: '1M',
    profile: 'Multimodal · Retrieval · Speed',
    strengths: 'Multimodal · Retrieval · Speed',
    cost: 'Medium',
    latency: 'Fast',
    multimodal: 'Text, images, audio and video',
  },
  {
    id: 'demo-llama',
    name: 'Llama 3 70B',
    provider: 'Meta / Open',
    tag: 'Private ready',
    context: '128K',
    profile: 'Open weights · Fine-tune · On-prem',
    strengths: 'Open weights · Fine-tune · On-prem',
    cost: 'Infrastructure dependent',
    latency: 'Infrastructure dependent',
    multimodal: 'Endpoint dependent',
  },
  {
    id: 'demo-mistral',
    name: 'Mistral Large',
    provider: 'Mistral AI',
    tag: 'EU ready',
    context: '128K',
    profile: 'Multilingual · Efficient · EU',
    strengths: 'Multilingual · Efficient · EU',
    cost: 'Endpoint dependent',
    latency: 'Endpoint dependent',
    multimodal: 'Endpoint dependent',
  },
  {
    id: 'demo-custom',
    name: 'Custom / Fine-tuned',
    provider: 'Your model',
    tag: 'Advanced',
    context: 'Varies',
    profile: 'Domain-specific · Maximum control',
    strengths: 'Domain-specific · Maximum control',
    cost: 'Endpoint dependent',
    latency: 'Endpoint dependent',
    multimodal: 'Endpoint dependent',
  },
];
