import {hasCapability} from './product-access';
export type HelpReply = {text:string;topic?:string};
type Topic={id:string;match:RegExp;level:'user'|'operator'|'admin';en:string;pt:string};
const topics:Topic[]=[
{id:'agents',match:/agent|agente|specialist|especialista|catalog|discover/,level:'user',en:'Open Discover to choose an agent and review its capabilities. Submit your request with what you need it to do; your Operations team prepares the knowledge, skills and connections. Follow the request in your workspace. An agent must be prepared and activated before it can run tasks.',pt:'Abra Discover para escolher um agente e revisar suas capacidades. Envie a solicitação explicando o que precisa; o time de Operations prepara os conhecimentos, skills e conexões. Acompanhe a solicitação no seu workspace. O agente precisa estar preparado e ativado antes de executar tarefas.'},
{id:'work',match:/\bwork\b|trabalh|resultado|result|pesquis|search|usar|use my/,level:'user',en:'Open My Agents, choose an available agent and use its Work tab. Describe your task and review the result and any cited sources. Your past work appears in Work. If the capability is unavailable, request preparation from Operations; Neo cannot activate or execute it for you.',pt:'Abra My Agents, escolha um agente disponível e use a aba Work. Descreva a tarefa e confira o resultado e as fontes citadas. O histórico aparece em Work. Se a capacidade estiver indisponível, solicite a preparação a Operations; o Neo não ativa nem executa o agente por você.'},
{id:'analytics',match:/analytic|anal[ií]tic|relat[oó]rio|report|desempenh|performance|metric/,level:'user',en:'Workspace → Analytics shows your own agent activity; Reports organizes your work. Inside an agent, its Analytics tab focuses on that agent. Company-wide operational reports belong to Operations, while costs belong to the administrator’s FinOps area. Missing data is not the same as zero activity.',pt:'Workspace → Analytics mostra a sua atividade com os agentes; Reports organiza o seu trabalho. Dentro de cada agente, a aba Analytics detalha aquele agente. Relatórios operacionais da empresa ficam em Operations; custos ficam em FinOps para administradores. Dados indisponíveis não significam atividade zero.'},
{id:'profile',match:/profile|perfil|senha|password|login|sign.?out|sair|account|conta/,level:'user',en:'Click your avatar or name in the header and choose Profile to view your account, or Sign out to leave. Use the login page’s password recovery if needed. Never send passwords or verification codes to Neo. An administrator manages workspace membership and access.',pt:'Clique no avatar ou no seu nome no header e escolha Profile para ver sua conta, ou Sign out para sair. Se necessário, use a recuperação de senha na tela de login. Nunca envie senhas ou códigos de verificação ao Neo. O administrador gerencia os vínculos e acessos ao workspace.'},
{id:'skills',match:/skill|habilidad|capabilit|capacidade/,level:'operator',en:'In Operations → Skills, create or select a reusable skill. Add it to the agent’s draft version, configure its required knowledge and tools, and validate it before release. Adding a skill expands the same agent; it does not create another Neo or automatically change an existing production version.',pt:'Em Operations → Skills, crie ou selecione uma skill reutilizável. Adicione-a à versão de rascunho do agente, configure os conhecimentos e ferramentas necessários e valide antes da liberação. Uma nova skill amplia o mesmo agente: não cria outro Neo nem altera automaticamente uma versão já em produção.'},
{id:'knowledge',match:/knowledge|conhecimento|document|fonte|source|upload/,level:'operator',en:'Use Operations → Knowledge to manage authorized documents, then select the sources the agent’s version can use. Check the content and retrieval evaluation before releasing it. A document being saved does not mean every agent automatically has access to it.',pt:'Use Operations → Knowledge para gerenciar documentos autorizados e selecione as fontes que a versão do agente poderá usar. Confira o conteúdo e a avaliação de busca antes de liberar. Salvar um documento não dá acesso automático a todos os agentes.'},
{id:'evaluations',match:/evaluat|avalia|valid|test|qualidade|quality/,level:'operator',en:'Use Operations → Evaluations to review checks for the selected agent version. Confirm the intended sources, inputs and expected outcomes, then investigate failed checks. Passing a retrieval check alone does not certify full production readiness.',pt:'Use Operations → Evaluations para revisar as verificações da versão do agente. Confirme fontes, entradas e resultados esperados e investigue falhas. Passar em uma verificação de busca não certifica, sozinho, que o agente está pronto para produção.'},
{id:'deployments',match:/deploy|ativ|activat|publicar|launch|produ[cç][aã]o|production|agentops|monitor/,level:'operator',en:'Review the agent version, evaluations, required approvals and available services before using Operations → Deployments. AgentOps is where you follow operational activity once connected. Saved configuration is not a live deployment. Neo can explain the steps but cannot approve or deploy for you.',pt:'Revise a versão do agente, avaliações, aprovações exigidas e serviços disponíveis antes de usar Operations → Deployments. AgentOps acompanha a atividade operacional quando conectada. Uma configuração salva não é uma implantação ativa. O Neo explica as etapas, mas não aprova nem publica por você.'},
{id:'costs',match:/finops|cost|custo|gasto|spend|billing|cobran|d[oó]lar|budget|or[cç]amento/,level:'admin',en:'Open Settings → FinOps for available company usage and cost controls. Review the period and data source before comparing agents or users. If provider usage is not connected, costs are unavailable, not zero. Neo cannot read your current bill or approve additional spending.',pt:'Abra Settings → FinOps para consultar os dados disponíveis de uso e custos da empresa. Confira o período e a origem dos dados antes de comparar agentes ou usuários. Sem a integração de consumo, o custo está indisponível, não zerado. O Neo não lê sua fatura atual nem aprova aumento de gastos.'},
{id:'access',match:/permission|permiss|acesso|access|usu[aá]rio|member|membro|pap[eé]is|role|admin/,level:'admin',en:'In Settings → People & access, review a member and choose User, AI Operator or Administrator. User accesses Workspace; AI Operator also accesses daily Operations; Administrator manages organization settings and FinOps. Check the person and intended scope before saving. Neo cannot grant permissions.',pt:'Em Settings → People & access, revise o membro e escolha User, AI Operator ou Administrator. User acessa Workspace; AI Operator também acessa Operations; Administrator gerencia configurações da empresa e FinOps. Confira a pessoa e o escopo antes de salvar. O Neo não concede permissões.'},
{id:'connections',match:/connect|conex|integra|model|modelo|provider|provedor|api|govern|pol[ií]tic|audit/,level:'admin',en:'Use Settings for Connections, Models, Governance and Audit Log. Review provider availability, permitted data and required policies before preparing agents. Do not paste API keys or credentials here. Operators should request administrative changes from their administrator.',pt:'Use Settings para Connections, Models, Governance e Audit Log. Confira a disponibilidade do provedor, os dados permitidos e as políticas exigidas antes de preparar agentes. Não cole chaves de API ou credenciais aqui. Operadores devem solicitar alterações administrativas ao administrador.'},
];
export function answerNeoHelp(message:string,role:string|undefined,previous?:string):HelpReply{
 const q=message.trim().toLowerCase();
 const pt=/[ãõçáéíóúêô]|\b(como|onde|quero|preciso|posso|meu|minha|ajuda|adicionar|criar|agente|custos|obrigad|ola|oi|sim)\b/.test(q);
 if(!q)return{text:pt?'O que você gostaria de fazer?':'What would you like to do?'};
 const normalized=q.normalize('NFD').replace(/[\u0300-\u036f]/g,'');
 let topic=topics.find(t=>!['agents','work'].includes(t.id)&&t.match.test(normalized)) ?? topics.find(t=>t.match.test(normalized));
 if(!topic && /\b(more|detail|next|explain|mais|detalhes|proximo|explique|isso)\b/.test(normalized))topic=topics.find(t=>t.id===previous);
 if(!topic){
  if(/^(hi|hello|hey|oi|ola)[!?.\s]*$/.test(normalized))return{text:pt?'Olá! Posso orientar sobre seus agentes, tarefas, analytics e conta. O que você quer fazer?':'Hello! I can guide you through agents, work, analytics and your account. What would you like to do?'};
  return{text:pt?'Ainda não encontrei uma orientação para essa pergunta. Você está tentando escolher um agente, usar uma skill, consultar resultados ou ajustar sua conta? Descreva a tela e o que deseja fazer. Esta ajuda usa o guia do produto; não consulta dados da sua empresa.':'I could not find guidance for that question yet. Are you choosing an agent, using a skill, reviewing results or adjusting your account? Describe the screen and what you want to do. This help uses the product guide; it does not look up your company data.'};
 }
 const allowed=topic.level==='user'||(topic.level==='operator'&&hasCapability(role,'operations:view'))||(topic.level==='admin'&&role==='Org Admin');
 if(!allowed)return{topic:topic.id,text:pt?(topic.level==='admin'?'Esse assunto é administrado pelo Administrator da sua empresa. Solicite a ele a alteração ou informação necessária. Posso orientar você sobre o uso dos seus agentes e resultados no Workspace.':'Essa preparação é feita pelo time de Operations. Abra o agente e descreva sua necessidade na solicitação da aba Work. O time revisa as fontes, skills e conexões necessárias.'):(topic.level==='admin'?'Your company Administrator manages this area. Ask them for the change or information you need. I can guide you through your agents and results in Workspace.':'Your Operations team handles this preparation. Open the agent and describe your need in a request from its Work tab. The team reviews the required sources, skills and connections.')};
 return{topic:topic.id,text:pt?topic.pt:topic.en};
}
